/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 55bbcb4c72a0
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { X402APIBaseError } from "./x402-api-base-error.js";

export type ApiErrorEnvelopeData = {
  error: models.ApiError;
};

export class ApiErrorEnvelope extends X402APIBaseError {
  error: models.ApiError;

  /** The original data that was passed to this error instance. */
  data$: ApiErrorEnvelopeData;

  constructor(
    err: ApiErrorEnvelopeData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ApiErrorEnvelope";
  }
}

/** @internal */
export const ApiErrorEnvelope$inboundSchema: z.ZodMiniType<
  ApiErrorEnvelope,
  unknown
> = z.pipe(
  z.object({
    error: models.ApiError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ApiErrorEnvelope(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
