/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 354e9665f7e0
 */

/** The base class for all HTTP error responses */
export class X402APIBaseError extends Error {
  /** HTTP meta data */
  public readonly httpMeta: {
    response: Response;
    request: Request;
    body: string;
  };

  constructor(
    message: string,
    httpMeta: {
      response: Response;
      request: Request;
      body: string;
    },
  ) {
    super(message);
    this.httpMeta = httpMeta;

    this.name = "X402APIBaseError";
  }
}
