/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chargesCreate } from "../funcs/charges-create.js";
import { chargesRetrieve } from "../funcs/charges-retrieve.js";
import { chargesSubmitPayment } from "../funcs/charges-submit-payment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Charges extends ClientSDK {
  /**
   * Create a programmatic charge
   *
   * @remarks
   * Create one idempotent dynamic charge and immutable PAYMENT-REQUIRED challenge from an active resource template. resource_version_id is the current active_version.id returned by GET /v1/resources, not the top-level resource id or pay_ public_payment_id. The 201 management response contains the canonical buyer challenge; it does not submit or settle payment. When direct human checkout is active and the frozen charge has an eligible sponsored rail, the response also contains paired human_checkout_url and qr_payload fields for the same exact charge. Requires a tenant API key with the `commerce:write` scope.
   */
  async create(
    request: operations.ChargesCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.ChargesCreateResponse> {
    return unwrapAsync(chargesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a programmatic charge
   *
   * @remarks
   * Retrieve the frozen terms and current projected status of a tenant charge. Any optional human_checkout_url and qr_payload are stable, identical bearer capabilities that expire with expires_at. Requires a tenant API key with the `commerce:read` scope.
   */
  async retrieve(
    request: operations.ChargesRetrieveRequest,
    options?: RequestOptions,
  ): Promise<operations.ChargesRetrieveResponse> {
    return unwrapAsync(chargesRetrieve(
      this,
      request,
      options,
    ));
  }

  /**
   * Submit a programmatic charge payment
   *
   * @remarks
   * Submit one exact canonical PAYMENT-SIGNATURE for a tenant charge. The request body is empty. HTTP 200 with confirmed=true means the payment is accepted and must not be resubmitted; finalized=true means the signed receipt is ready. Preserve and retry the identical signature after HTTP 202 or 503; never create a replacement authorization for an ambiguous outcome. Requires a tenant API key with the `commerce:write` scope.
   */
  async submitPayment(
    request: operations.ChargesSubmitPaymentRequest,
    options?: RequestOptions,
  ): Promise<operations.ChargesSubmitPaymentResponse> {
    return unwrapAsync(chargesSubmitPayment(
      this,
      request,
      options,
    ));
  }
}
