/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d5ffe6668ea
 */

import { chargesCreate } from "../funcs/charges-create.js";
import { chargesRetrieve } from "../funcs/charges-retrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Charges extends ClientSDK {
  /**
   * Create a programmatic charge
   *
   * @remarks
   * Create one idempotent dynamic charge with immutable x402 payment terms.
   */
  async create(
    request: operations.ChargesCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.ChargesCreateResponse> {
    return unwrapAsync(chargesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a programmatic charge
   *
   * @remarks
   * Retrieve the frozen terms and current projected status of a tenant charge.
   */
  async retrieve(
    request: operations.ChargesRetrieveRequest,
    options?: RequestOptions,
  ): Promise<operations.ChargesRetrieveResponse> {
    return unwrapAsync(chargesRetrieve(
      this,
      request,
      options,
    ));
  }
}
