/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { facilitatorGetSupported } from "../funcs/facilitator-get-supported.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Facilitator extends ClientSDK {
  /**
   * Get supported facilitator profiles
   *
   * @remarks
   * Return the currently approved public x402 facilitator profiles. Public endpoint; no API key or scope is required.
   */
  async getSupported(
    options?: RequestOptions,
  ): Promise<operations.FacilitatorGetSupportedResponse> {
    return unwrapAsync(facilitatorGetSupported(
      this,
      options,
    ));
  }
}
