/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b7b92e67c726
 */

import { idempotencyGetOutcome } from "../funcs/idempotency-get-outcome.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Idempotency extends ClientSDK {
  /**
   * Get an idempotency outcome
   *
   * @remarks
   * Return the authoritative tenant-scoped outcome for a durable mutation key.
   */
  async getOutcome(
    request: operations.IdempotencyGetOutcomeRequest,
    options?: RequestOptions,
  ): Promise<operations.IdempotencyGetOutcomeResponse> {
    return unwrapAsync(idempotencyGetOutcome(
      this,
      request,
      options,
    ));
  }
}
