/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 97fbf5e9ab63
 */

import { networkFeesCreateQuote } from "../funcs/network-fees-create-quote.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class NetworkFees extends ClientSDK {
  /**
   * Create a network-fee quote
   *
   * @remarks
   * Preview bounded network fees for the requested resource prices and rails.
   */
  async createQuote(
    request: models.NetworkFeePreview,
    options?: RequestOptions,
  ): Promise<operations.NetworkFeesCreateQuoteResponse> {
    return unwrapAsync(networkFeesCreateQuote(
      this,
      request,
      options,
    ));
  }
}
