/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b318c92b1ee9
 */

import { ordersList } from "../funcs/orders-list.js";
import { ordersRetrieve } from "../funcs/orders-retrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Orders extends ClientSDK {
  /**
   * List orders
   *
   * @remarks
   * List tenant-visible orders using opaque cursor pagination.
   */
  async list(
    request?: operations.OrdersListRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.OrdersListResponse> {
    return unwrapAsync(ordersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve an order
   *
   * @remarks
   * Retrieve one tenant-visible order by its canonical identifier.
   */
  async retrieve(
    request: operations.OrdersRetrieveRequest,
    options?: RequestOptions,
  ): Promise<operations.OrdersRetrieveResponse> {
    return unwrapAsync(ordersRetrieve(
      this,
      request,
      options,
    ));
  }
}
