/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f059d3c1d898
 */

import { paymentsListObservations } from "../funcs/payments-list-observations.js";
import { paymentsList } from "../funcs/payments-list.js";
import { paymentsRetrieveReceipt } from "../funcs/payments-retrieve-receipt.js";
import { paymentsRetrieve } from "../funcs/payments-retrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * List payments
   *
   * @remarks
   * List tenant-visible payments using opaque cursor pagination.
   */
  async list(
    request?: operations.PaymentsListRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PaymentsListResponse> {
    return unwrapAsync(paymentsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a payment
   *
   * @remarks
   * Retrieve one tenant-visible payment by its canonical identifier.
   */
  async retrieve(
    request: operations.PaymentsRetrieveRequest,
    options?: RequestOptions,
  ): Promise<operations.PaymentsRetrieveResponse> {
    return unwrapAsync(paymentsRetrieve(
      this,
      request,
      options,
    ));
  }

  /**
   * List payment observations
   *
   * @remarks
   * List finalized and pending chain observations for one tenant-visible payment.
   */
  async listObservations(
    request: operations.PaymentsListObservationsRequest,
    options?: RequestOptions,
  ): Promise<operations.PaymentsListObservationsResponse> {
    return unwrapAsync(paymentsListObservations(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a payment receipt
   *
   * @remarks
   * Retrieve the signed receipt projection for one tenant-visible payment.
   */
  async retrieveReceipt(
    request: operations.PaymentsRetrieveReceiptRequest,
    options?: RequestOptions,
  ): Promise<operations.PaymentsRetrieveReceiptResponse> {
    return unwrapAsync(paymentsRetrieveReceipt(
      this,
      request,
      options,
    ));
  }
}
