/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4834fe454116
 */

import { paymentReadinessRetrieve } from "../funcs/payment-readiness-retrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PaymentReadiness extends ClientSDK {
  /**
   * Retrieve payment readiness
   *
   * @remarks
   * Return the tenant's current external-wallet payment-readiness projection.
   */
  async retrieve(
    options?: RequestOptions,
  ): Promise<operations.PaymentReadinessRetrieveResponse> {
    return unwrapAsync(paymentReadinessRetrieve(
      this,
      options,
    ));
  }
}
