/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbfeb000bb6b
 */

import { receiptVerificationKeysRetrieve } from "../funcs/receipt-verification-keys-retrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ReceiptVerificationKeys extends ClientSDK {
  /**
   * Retrieve receipt verification keys
   *
   * @remarks
   * Return the public receipt verification-key history for out-of-band-pinned verification.
   */
  async retrieve(
    options?: RequestOptions,
  ): Promise<operations.ReceiptVerificationKeysRetrieveResponse> {
    return unwrapAsync(receiptVerificationKeysRetrieve(
      this,
      options,
    ));
  }
}
