/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 88c1f1d0f649
 */

import { receivingAddressesActivate } from "../funcs/receiving-addresses-activate.js";
import { receivingAddressesCreateControlChallenge } from "../funcs/receiving-addresses-create-control-challenge.js";
import { receivingAddressesGetControlCapabilities } from "../funcs/receiving-addresses-get-control-capabilities.js";
import { receivingAddressesList } from "../funcs/receiving-addresses-list.js";
import { receivingAddressesRefreshReadiness } from "../funcs/receiving-addresses-refresh-readiness.js";
import { receivingAddressesRegister } from "../funcs/receiving-addresses-register.js";
import { receivingAddressesRotate } from "../funcs/receiving-addresses-rotate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ReceivingAddresses extends ClientSDK {
  /**
   * Get receiving-address control capabilities
   *
   * @remarks
   * Return the supported proof and control capabilities for external receiving addresses.
   */
  async getControlCapabilities(
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesGetControlCapabilitiesResponse> {
    return unwrapAsync(receivingAddressesGetControlCapabilities(
      this,
      options,
    ));
  }

  /**
   * Create a receiving-address control challenge
   *
   * @remarks
   * Create an idempotent proof-of-control challenge for an external receiving address.
   */
  async createControlChallenge(
    request: operations.ReceivingAddressesCreateControlChallengeRequest,
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesCreateControlChallengeResponse> {
    return unwrapAsync(receivingAddressesCreateControlChallenge(
      this,
      request,
      options,
    ));
  }

  /**
   * List receiving addresses
   *
   * @remarks
   * List tenant receiving-address registrations using opaque cursor pagination.
   */
  async list(
    request?: operations.ReceivingAddressesListRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesListResponse> {
    return unwrapAsync(receivingAddressesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Register a receiving address
   *
   * @remarks
   * Register a proven external receiving address without transferring wallet custody.
   */
  async register(
    request: operations.ReceivingAddressesRegisterRequest,
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesRegisterResponse> {
    return unwrapAsync(receivingAddressesRegister(
      this,
      request,
      options,
    ));
  }

  /**
   * Activate a receiving address
   *
   * @remarks
   * Activate a ready external receiving-address registration idempotently.
   */
  async activate(
    request: operations.ReceivingAddressesActivateRequest,
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesActivateResponse> {
    return unwrapAsync(receivingAddressesActivate(
      this,
      request,
      options,
    ));
  }

  /**
   * Refresh receiving-address readiness
   *
   * @remarks
   * Request an idempotent refresh of external receiving-address readiness evidence.
   */
  async refreshReadiness(
    request: operations.ReceivingAddressesRefreshReadinessRequest,
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesRefreshReadinessResponse> {
    return unwrapAsync(receivingAddressesRefreshReadiness(
      this,
      request,
      options,
    ));
  }

  /**
   * Rotate a receiving address
   *
   * @remarks
   * Create an idempotent receiving-address rotation from a proven replacement.
   */
  async rotate(
    request: operations.ReceivingAddressesRotateRequest,
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesRotateResponse> {
    return unwrapAsync(receivingAddressesRotate(
      this,
      request,
      options,
    ));
  }
}
