/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { receivingAddressesGetControlCapabilities } from "../funcs/receiving-addresses-get-control-capabilities.js";
import { receivingAddressesList } from "../funcs/receiving-addresses-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ReceivingAddresses extends ClientSDK {
  /**
   * Get receiving-address control capabilities
   *
   * @remarks
   * Return the supported proof and control capabilities for external receiving addresses. Requires a tenant API key with the `wallets:read` scope.
   */
  async getControlCapabilities(
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesGetControlCapabilitiesResponse> {
    return unwrapAsync(receivingAddressesGetControlCapabilities(
      this,
      options,
    ));
  }

  /**
   * List receiving addresses
   *
   * @remarks
   * List tenant receiving-address registrations using opaque cursor pagination. Requires a tenant API key with the `wallets:read` scope.
   */
  async list(
    request?: operations.ReceivingAddressesListRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ReceivingAddressesListResponse> {
    return unwrapAsync(receivingAddressesList(
      this,
      request,
      options,
    ));
  }
}
