/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesCreateVersion } from "../funcs/resources-create-version.js";
import { resourcesCreate } from "../funcs/resources-create.js";
import { resourcesListVersions } from "../funcs/resources-list-versions.js";
import { resourcesList } from "../funcs/resources-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Resources extends ClientSDK {
  /**
   * List resources
   *
   * @remarks
   * List tenant resources and their visible versions using opaque cursor pagination. Requires a tenant API key with the `resources:read` scope.
   */
  async list(
    request?: operations.ResourcesListRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ResourcesListResponse> {
    return unwrapAsync(resourcesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a resource
   *
   * @remarks
   * Create one tenant resource idempotently. Requires a tenant API key with the `resources:write` scope.
   */
  async create(
    request: operations.ResourcesCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.ResourcesCreateResponse> {
    return unwrapAsync(resourcesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List resource versions
   *
   * @remarks
   * List immutable versions of one tenant resource using opaque cursor pagination. Requires a tenant API key with the `resources:read` scope.
   */
  async listVersions(
    request: operations.ResourcesListVersionsRequest,
    options?: RequestOptions,
  ): Promise<operations.ResourcesListVersionsResponse> {
    return unwrapAsync(resourcesListVersions(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a resource version
   *
   * @remarks
   * Create an immutable priced version of one tenant resource idempotently. Requires a tenant API key with the `resources:write` scope.
   */
  async createVersion(
    request: operations.ResourcesCreateVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.ResourcesCreateVersionResponse> {
    return unwrapAsync(resourcesCreateVersion(
      this,
      request,
      options,
    ));
  }
}
