/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 784571af2f69
 */

import { ClientSDK } from "../lib/sdks.js";
import { Charges } from "./charges.js";
import { Facilitator } from "./facilitator.js";
import { Idempotency } from "./idempotency.js";
import { NetworkFees } from "./network-fees.js";
import { Orders } from "./orders.js";
import { PaymentReadiness } from "./payment-readiness.js";
import { Payments } from "./payments.js";
import { ReceiptVerificationKeys } from "./receipt-verification-keys.js";
import { ReceivingAddresses } from "./receiving-addresses.js";
import { Resources } from "./resources.js";
import { Wallets } from "./wallets.js";

export class X402Api extends ClientSDK {
  private _charges?: Charges;
  get charges(): Charges {
    return (this._charges ??= new Charges(this._options));
  }

  private _facilitator?: Facilitator;
  get facilitator(): Facilitator {
    return (this._facilitator ??= new Facilitator(this._options));
  }

  private _idempotency?: Idempotency;
  get idempotency(): Idempotency {
    return (this._idempotency ??= new Idempotency(this._options));
  }

  private _networkFees?: NetworkFees;
  get networkFees(): NetworkFees {
    return (this._networkFees ??= new NetworkFees(this._options));
  }

  private _orders?: Orders;
  get orders(): Orders {
    return (this._orders ??= new Orders(this._options));
  }

  private _paymentReadiness?: PaymentReadiness;
  get paymentReadiness(): PaymentReadiness {
    return (this._paymentReadiness ??= new PaymentReadiness(this._options));
  }

  private _receiptVerificationKeys?: ReceiptVerificationKeys;
  get receiptVerificationKeys(): ReceiptVerificationKeys {
    return (this._receiptVerificationKeys ??= new ReceiptVerificationKeys(
      this._options,
    ));
  }

  private _payments?: Payments;
  get payments(): Payments {
    return (this._payments ??= new Payments(this._options));
  }

  private _receivingAddresses?: ReceivingAddresses;
  get receivingAddresses(): ReceivingAddresses {
    return (this._receivingAddresses ??= new ReceivingAddresses(this._options));
  }

  private _resources?: Resources;
  get resources(): Resources {
    return (this._resources ??= new Resources(this._options));
  }

  private _wallets?: Wallets;
  get wallets(): Wallets {
    return (this._wallets ??= new Wallets(this._options));
  }
}
