/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a9ad586bb9ab
 */

import { walletsRetrieveBalance } from "../funcs/wallets-retrieve-balance.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Wallets extends ClientSDK {
  /**
   * Retrieve wallet balances
   *
   * @remarks
   * Retrieve finalized external-wallet balance observations at the requested finality.
   */
  async retrieveBalance(
    request: operations.WalletsRetrieveBalanceRequest,
    options?: RequestOptions,
  ): Promise<operations.WalletsRetrieveBalanceResponse> {
    return unwrapAsync(walletsRetrieveBalance(
      this,
      request,
      options,
    ));
  }
}
