/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dd18bfc44b04
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @x402api/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx chargesCreate.example.ts
 */

import { X402Api } from "@x402api/sdk";

const x402Api = new X402Api({
  tenantApiKey: process.env["X402API_TENANT_API_KEY"] ?? "",
});

async function main() {
  const result = await x402Api.charges.create({
    idempotencyKey: "charge-example-001",
    body: {
      resourceVersionId: "00000000-0000-4000-8000-000000000001",
      resourceUrl: "https://merchant.example.com/premium-report",
      prices: [
        {
          assetId: "base_usdc",
          amountAtomic: "1000000",
        },
      ],
      expiresInSeconds: 900,
    },
  });

  console.log(result);
}

main().catch(console.error);
