/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ChargesSubmitPaymentRequest = {
  /**
   * Canonical base64-encoded x402 v2 PaymentPayload.
   */
  paymentSignature: string;
  chargeId: string;
};

export type ChargesSubmitPaymentResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for submit a programmatic charge payment.
   */
  dynamicChargePaymentResponse?:
    | models.DynamicChargePaymentResponse
    | undefined;
  /**
   * The request failed.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ChargesSubmitPaymentRequest$Outbound = {
  "PAYMENT-SIGNATURE": string;
  charge_id: string;
};

/** @internal */
export const ChargesSubmitPaymentRequest$outboundSchema: z.ZodMiniType<
  ChargesSubmitPaymentRequest$Outbound,
  ChargesSubmitPaymentRequest
> = z.pipe(
  z.object({
    paymentSignature: z.string(),
    chargeId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      paymentSignature: "PAYMENT-SIGNATURE",
      chargeId: "charge_id",
    });
  }),
);

export function chargesSubmitPaymentRequestToJSON(
  chargesSubmitPaymentRequest: ChargesSubmitPaymentRequest,
): string {
  return JSON.stringify(
    ChargesSubmitPaymentRequest$outboundSchema.parse(
      chargesSubmitPaymentRequest,
    ),
  );
}

/** @internal */
export const ChargesSubmitPaymentResponse$inboundSchema: z.ZodMiniType<
  ChargesSubmitPaymentResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    DynamicChargePaymentResponse: types.optional(
      models.DynamicChargePaymentResponse$inboundSchema,
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "DynamicChargePaymentResponse": "dynamicChargePaymentResponse",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function chargesSubmitPaymentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChargesSubmitPaymentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChargesSubmitPaymentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChargesSubmitPaymentResponse' from JSON`,
  );
}
