/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4311c9af18ec
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ChargesRetrieveRequest = {
  chargeId: string;
};

export type ChargesRetrieveResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for retrieve a programmatic charge.
   */
  dynamicChargeResponse?: models.DynamicChargeResponse | undefined;
  /**
   * The request failed.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ChargesRetrieveRequest$Outbound = {
  charge_id: string;
};

/** @internal */
export const ChargesRetrieveRequest$outboundSchema: z.ZodMiniType<
  ChargesRetrieveRequest$Outbound,
  ChargesRetrieveRequest
> = z.pipe(
  z.object({
    chargeId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      chargeId: "charge_id",
    });
  }),
);

export function chargesRetrieveRequestToJSON(
  chargesRetrieveRequest: ChargesRetrieveRequest,
): string {
  return JSON.stringify(
    ChargesRetrieveRequest$outboundSchema.parse(chargesRetrieveRequest),
  );
}

/** @internal */
export const ChargesRetrieveResponse$inboundSchema: z.ZodMiniType<
  ChargesRetrieveResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    DynamicChargeResponse: types.optional(
      models.DynamicChargeResponse$inboundSchema,
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "DynamicChargeResponse": "dynamicChargeResponse",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function chargesRetrieveResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChargesRetrieveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChargesRetrieveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChargesRetrieveResponse' from JSON`,
  );
}
