/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f63c8a7cf382
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ChargesCreateRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  body: models.DynamicChargeCreate;
};

export type ChargesCreateResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for create a programmatic charge.
   */
  dynamicChargeResponse?: models.DynamicChargeResponse | undefined;
  /**
   * The request failed.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ChargesCreateRequest$Outbound = {
  "Idempotency-Key": string;
  body: models.DynamicChargeCreate$Outbound;
};

/** @internal */
export const ChargesCreateRequest$outboundSchema: z.ZodMiniType<
  ChargesCreateRequest$Outbound,
  ChargesCreateRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    body: models.DynamicChargeCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function chargesCreateRequestToJSON(
  chargesCreateRequest: ChargesCreateRequest,
): string {
  return JSON.stringify(
    ChargesCreateRequest$outboundSchema.parse(chargesCreateRequest),
  );
}

/** @internal */
export const ChargesCreateResponse$inboundSchema: z.ZodMiniType<
  ChargesCreateResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    DynamicChargeResponse: types.optional(
      models.DynamicChargeResponse$inboundSchema,
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "DynamicChargeResponse": "dynamicChargeResponse",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function chargesCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChargesCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChargesCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChargesCreateResponse' from JSON`,
  );
}
