/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ae6cd72001db
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type FacilitatorGetSupportedResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for get supported facilitator profiles.
   */
  supportedResponse?: models.SupportedResponse | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export const FacilitatorGetSupportedResponse$inboundSchema: z.ZodMiniType<
  FacilitatorGetSupportedResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    SupportedResponse: types.optional(models.SupportedResponse$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "SupportedResponse": "supportedResponse",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function facilitatorGetSupportedResponseFromJSON(
  jsonString: string,
): SafeParseResult<FacilitatorGetSupportedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FacilitatorGetSupportedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FacilitatorGetSupportedResponse' from JSON`,
  );
}
