/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4915dc871d96
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type IdempotencyGetOutcomeRequest = {
  idempotencyKey: string;
};

export type IdempotencyGetOutcomeResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for get an idempotency outcome.
   */
  idempotencyOutcome?: models.IdempotencyOutcome | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type IdempotencyGetOutcomeRequest$Outbound = {
  idempotency_key: string;
};

/** @internal */
export const IdempotencyGetOutcomeRequest$outboundSchema: z.ZodMiniType<
  IdempotencyGetOutcomeRequest$Outbound,
  IdempotencyGetOutcomeRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency_key",
    });
  }),
);

export function idempotencyGetOutcomeRequestToJSON(
  idempotencyGetOutcomeRequest: IdempotencyGetOutcomeRequest,
): string {
  return JSON.stringify(
    IdempotencyGetOutcomeRequest$outboundSchema.parse(
      idempotencyGetOutcomeRequest,
    ),
  );
}

/** @internal */
export const IdempotencyGetOutcomeResponse$inboundSchema: z.ZodMiniType<
  IdempotencyGetOutcomeResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    IdempotencyOutcome: types.optional(models.IdempotencyOutcome$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "IdempotencyOutcome": "idempotencyOutcome",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function idempotencyGetOutcomeResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdempotencyGetOutcomeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdempotencyGetOutcomeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdempotencyGetOutcomeResponse' from JSON`,
  );
}
