/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 147c70eafede
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type NetworkFeesCreateQuoteResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for create a network-fee quote.
   */
  networkFeePreviewResponse?: models.NetworkFeePreviewResponse | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export const NetworkFeesCreateQuoteResponse$inboundSchema: z.ZodMiniType<
  NetworkFeesCreateQuoteResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    NetworkFeePreviewResponse: types.optional(
      models.NetworkFeePreviewResponse$inboundSchema,
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "NetworkFeePreviewResponse": "networkFeePreviewResponse",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function networkFeesCreateQuoteResponseFromJSON(
  jsonString: string,
): SafeParseResult<NetworkFeesCreateQuoteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkFeesCreateQuoteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkFeesCreateQuoteResponse' from JSON`,
  );
}
