/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7d418e93b369
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OrdersRetrieveRequest = {
  id: string;
};

export type OrdersRetrieveResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for retrieve an order.
   */
  order?: models.Order | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type OrdersRetrieveRequest$Outbound = {
  id: string;
};

/** @internal */
export const OrdersRetrieveRequest$outboundSchema: z.ZodMiniType<
  OrdersRetrieveRequest$Outbound,
  OrdersRetrieveRequest
> = z.object({
  id: z.string(),
});

export function ordersRetrieveRequestToJSON(
  ordersRetrieveRequest: OrdersRetrieveRequest,
): string {
  return JSON.stringify(
    OrdersRetrieveRequest$outboundSchema.parse(ordersRetrieveRequest),
  );
}

/** @internal */
export const OrdersRetrieveResponse$inboundSchema: z.ZodMiniType<
  OrdersRetrieveResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    Order: types.optional(models.Order$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Order": "order",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function ordersRetrieveResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrdersRetrieveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrdersRetrieveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrdersRetrieveResponse' from JSON`,
  );
}
