/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b2a279452216
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OrdersListRequest = {
  /**
   * Opaque pagination cursor from X-X402API-Next-Cursor or rel=next Link.
   */
  cursor?: string | undefined;
  /**
   * Number of results in the bounded array page (default and maximum 100).
   */
  pageSize?: number | undefined;
};

export type OrdersListResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for list orders.
   */
  paginatedOrderList?: Array<models.Order> | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type OrdersListRequest$Outbound = {
  cursor?: string | undefined;
  page_size: number;
};

/** @internal */
export const OrdersListRequest$outboundSchema: z.ZodMiniType<
  OrdersListRequest$Outbound,
  OrdersListRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    pageSize: z._default(z.int(), 100),
  }),
  z.transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
    });
  }),
);

export function ordersListRequestToJSON(
  ordersListRequest: OrdersListRequest,
): string {
  return JSON.stringify(
    OrdersListRequest$outboundSchema.parse(ordersListRequest),
  );
}

/** @internal */
export const OrdersListResponse$inboundSchema: z.ZodMiniType<
  OrdersListResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    PaginatedOrderList: types.optional(z.array(models.Order$inboundSchema)),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PaginatedOrderList": "paginatedOrderList",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function ordersListResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrdersListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrdersListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrdersListResponse' from JSON`,
  );
}
