/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a65f411c900
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PaymentsListObservationsRequest = {
  /**
   * Opaque pagination cursor from X-X402API-Next-Cursor or rel=next Link.
   */
  cursor?: string | undefined;
  id: string;
  /**
   * Number of results in the bounded array page (default and maximum 100).
   */
  pageSize?: number | undefined;
};

export type PaymentsListObservationsResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for list payment observations.
   */
  paginatedSettlementChainObservationList?:
    | Array<models.SettlementChainObservation>
    | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type PaymentsListObservationsRequest$Outbound = {
  cursor?: string | undefined;
  id: string;
  page_size: number;
};

/** @internal */
export const PaymentsListObservationsRequest$outboundSchema: z.ZodMiniType<
  PaymentsListObservationsRequest$Outbound,
  PaymentsListObservationsRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    id: z.string(),
    pageSize: z._default(z.int(), 100),
  }),
  z.transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
    });
  }),
);

export function paymentsListObservationsRequestToJSON(
  paymentsListObservationsRequest: PaymentsListObservationsRequest,
): string {
  return JSON.stringify(
    PaymentsListObservationsRequest$outboundSchema.parse(
      paymentsListObservationsRequest,
    ),
  );
}

/** @internal */
export const PaymentsListObservationsResponse$inboundSchema: z.ZodMiniType<
  PaymentsListObservationsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    PaginatedSettlementChainObservationList: types.optional(
      z.array(models.SettlementChainObservation$inboundSchema),
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PaginatedSettlementChainObservationList":
        "paginatedSettlementChainObservationList",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function paymentsListObservationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentsListObservationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentsListObservationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentsListObservationsResponse' from JSON`,
  );
}
