/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 92fc2a5b6d39
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PaymentReadinessRetrieveResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for retrieve payment readiness.
   */
  paymentReadiness?: models.PaymentReadiness | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export const PaymentReadinessRetrieveResponse$inboundSchema: z.ZodMiniType<
  PaymentReadinessRetrieveResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    PaymentReadiness: types.optional(models.PaymentReadiness$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PaymentReadiness": "paymentReadiness",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function paymentReadinessRetrieveResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReadinessRetrieveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReadinessRetrieveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReadinessRetrieveResponse' from JSON`,
  );
}
