/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 50ed88847a47
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PaymentsListRequest = {
  /**
   * Opaque pagination cursor from X-X402API-Next-Cursor or rel=next Link.
   */
  cursor?: string | undefined;
  /**
   * Number of results in the bounded array page (default and maximum 100).
   */
  pageSize?: number | undefined;
};

export type PaymentsListResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for list payments.
   */
  paginatedSettlementJobList?: Array<models.SettlementJob> | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type PaymentsListRequest$Outbound = {
  cursor?: string | undefined;
  page_size: number;
};

/** @internal */
export const PaymentsListRequest$outboundSchema: z.ZodMiniType<
  PaymentsListRequest$Outbound,
  PaymentsListRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    pageSize: z._default(z.int(), 100),
  }),
  z.transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
    });
  }),
);

export function paymentsListRequestToJSON(
  paymentsListRequest: PaymentsListRequest,
): string {
  return JSON.stringify(
    PaymentsListRequest$outboundSchema.parse(paymentsListRequest),
  );
}

/** @internal */
export const PaymentsListResponse$inboundSchema: z.ZodMiniType<
  PaymentsListResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    PaginatedSettlementJobList: types.optional(
      z.array(models.SettlementJob$inboundSchema),
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PaginatedSettlementJobList": "paginatedSettlementJobList",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function paymentsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentsListResponse' from JSON`,
  );
}
