/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2a77d971ce1b
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PaymentsRetrieveRequest = {
  id: string;
};

export type PaymentsRetrieveResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for retrieve a payment.
   */
  settlementJob?: models.SettlementJob | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type PaymentsRetrieveRequest$Outbound = {
  id: string;
};

/** @internal */
export const PaymentsRetrieveRequest$outboundSchema: z.ZodMiniType<
  PaymentsRetrieveRequest$Outbound,
  PaymentsRetrieveRequest
> = z.object({
  id: z.string(),
});

export function paymentsRetrieveRequestToJSON(
  paymentsRetrieveRequest: PaymentsRetrieveRequest,
): string {
  return JSON.stringify(
    PaymentsRetrieveRequest$outboundSchema.parse(paymentsRetrieveRequest),
  );
}

/** @internal */
export const PaymentsRetrieveResponse$inboundSchema: z.ZodMiniType<
  PaymentsRetrieveResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    SettlementJob: types.optional(models.SettlementJob$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "SettlementJob": "settlementJob",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function paymentsRetrieveResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentsRetrieveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentsRetrieveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentsRetrieveResponse' from JSON`,
  );
}
