/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fe19b42f4c2a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PaymentsRetrieveReceiptRequest = {
  id: string;
};

export type PaymentsRetrieveReceiptResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for retrieve a payment receipt.
   */
  paymentReceipt?: models.PaymentReceipt | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type PaymentsRetrieveReceiptRequest$Outbound = {
  id: string;
};

/** @internal */
export const PaymentsRetrieveReceiptRequest$outboundSchema: z.ZodMiniType<
  PaymentsRetrieveReceiptRequest$Outbound,
  PaymentsRetrieveReceiptRequest
> = z.object({
  id: z.string(),
});

export function paymentsRetrieveReceiptRequestToJSON(
  paymentsRetrieveReceiptRequest: PaymentsRetrieveReceiptRequest,
): string {
  return JSON.stringify(
    PaymentsRetrieveReceiptRequest$outboundSchema.parse(
      paymentsRetrieveReceiptRequest,
    ),
  );
}

/** @internal */
export const PaymentsRetrieveReceiptResponse$inboundSchema: z.ZodMiniType<
  PaymentsRetrieveReceiptResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    PaymentReceipt: types.optional(models.PaymentReceipt$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PaymentReceipt": "paymentReceipt",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function paymentsRetrieveReceiptResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentsRetrieveReceiptResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentsRetrieveReceiptResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentsRetrieveReceiptResponse' from JSON`,
  );
}
