/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bb5a942e9df3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReceivingAddressesListRequest = {
  /**
   * Opaque pagination cursor from X-X402API-Next-Cursor or rel=next Link.
   */
  cursor?: string | undefined;
  /**
   * Number of results in the bounded array page (default and maximum 100).
   */
  pageSize?: number | undefined;
};

export type ReceivingAddressesListResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for list receiving addresses.
   */
  paginatedExternalReceivingAddressList?:
    | Array<models.ExternalReceivingAddress>
    | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ReceivingAddressesListRequest$Outbound = {
  cursor?: string | undefined;
  page_size: number;
};

/** @internal */
export const ReceivingAddressesListRequest$outboundSchema: z.ZodMiniType<
  ReceivingAddressesListRequest$Outbound,
  ReceivingAddressesListRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    pageSize: z._default(z.int(), 100),
  }),
  z.transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
    });
  }),
);

export function receivingAddressesListRequestToJSON(
  receivingAddressesListRequest: ReceivingAddressesListRequest,
): string {
  return JSON.stringify(
    ReceivingAddressesListRequest$outboundSchema.parse(
      receivingAddressesListRequest,
    ),
  );
}

/** @internal */
export const ReceivingAddressesListResponse$inboundSchema: z.ZodMiniType<
  ReceivingAddressesListResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    PaginatedExternalReceivingAddressList: types.optional(
      z.array(models.ExternalReceivingAddress$inboundSchema),
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PaginatedExternalReceivingAddressList":
        "paginatedExternalReceivingAddressList",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function receivingAddressesListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReceivingAddressesListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReceivingAddressesListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceivingAddressesListResponse' from JSON`,
  );
}
