/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 05029a74ca10
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReceivingAddressesGetControlCapabilitiesResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for get receiving-address control capabilities.
   */
  externalAddressControlCapabilities?:
    | models.ExternalAddressControlCapabilities
    | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export const ReceivingAddressesGetControlCapabilitiesResponse$inboundSchema:
  z.ZodMiniType<ReceivingAddressesGetControlCapabilitiesResponse, unknown> = z
    .pipe(
      z.object({
        HttpMeta: models.HTTPMetadata$inboundSchema,
        ExternalAddressControlCapabilities: types.optional(
          models.ExternalAddressControlCapabilities$inboundSchema,
        ),
        ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
      }),
      z.transform((v) => {
        return remap$(v, {
          "HttpMeta": "httpMeta",
          "ExternalAddressControlCapabilities":
            "externalAddressControlCapabilities",
          "ApiErrorEnvelope": "apiErrorEnvelope",
        });
      }),
    );

export function receivingAddressesGetControlCapabilitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ReceivingAddressesGetControlCapabilitiesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ReceivingAddressesGetControlCapabilitiesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ReceivingAddressesGetControlCapabilitiesResponse' from JSON`,
  );
}
