/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 22502d707023
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReceiptVerificationKeysRetrieveResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for retrieve receipt verification keys.
   */
  receiptVerificationKeyHistory?:
    | models.ReceiptVerificationKeyHistory
    | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export const ReceiptVerificationKeysRetrieveResponse$inboundSchema:
  z.ZodMiniType<ReceiptVerificationKeysRetrieveResponse, unknown> = z.pipe(
    z.object({
      HttpMeta: models.HTTPMetadata$inboundSchema,
      ReceiptVerificationKeyHistory: types.optional(
        models.ReceiptVerificationKeyHistory$inboundSchema,
      ),
      ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "HttpMeta": "httpMeta",
        "ReceiptVerificationKeyHistory": "receiptVerificationKeyHistory",
        "ApiErrorEnvelope": "apiErrorEnvelope",
      });
    }),
  );

export function receiptVerificationKeysRetrieveResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ReceiptVerificationKeysRetrieveResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ReceiptVerificationKeysRetrieveResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ReceiptVerificationKeysRetrieveResponse' from JSON`,
  );
}
