/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e12478a84876
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReceivingAddressesRotateRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  readinessId: string;
  body: models.ExternalReceivingAddressRotation;
};

export type ReceivingAddressesRotateResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for rotate a receiving address.
   */
  externalReceivingAddress?: models.ExternalReceivingAddress | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ReceivingAddressesRotateRequest$Outbound = {
  "Idempotency-Key": string;
  readiness_id: string;
  body: models.ExternalReceivingAddressRotation$Outbound;
};

/** @internal */
export const ReceivingAddressesRotateRequest$outboundSchema: z.ZodMiniType<
  ReceivingAddressesRotateRequest$Outbound,
  ReceivingAddressesRotateRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    readinessId: z.string(),
    body: models.ExternalReceivingAddressRotation$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
      readinessId: "readiness_id",
    });
  }),
);

export function receivingAddressesRotateRequestToJSON(
  receivingAddressesRotateRequest: ReceivingAddressesRotateRequest,
): string {
  return JSON.stringify(
    ReceivingAddressesRotateRequest$outboundSchema.parse(
      receivingAddressesRotateRequest,
    ),
  );
}

/** @internal */
export const ReceivingAddressesRotateResponse$inboundSchema: z.ZodMiniType<
  ReceivingAddressesRotateResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    ExternalReceivingAddress: types.optional(
      models.ExternalReceivingAddress$inboundSchema,
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ExternalReceivingAddress": "externalReceivingAddress",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function receivingAddressesRotateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReceivingAddressesRotateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReceivingAddressesRotateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceivingAddressesRotateResponse' from JSON`,
  );
}
