/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 85ab5e744ba9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReceivingAddressesRefreshReadinessRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  readinessId: string;
};

export type ReceivingAddressesRefreshReadinessResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for refresh receiving-address readiness.
   */
  externalReceivingAddress?: models.ExternalReceivingAddress | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ReceivingAddressesRefreshReadinessRequest$Outbound = {
  "Idempotency-Key": string;
  readiness_id: string;
};

/** @internal */
export const ReceivingAddressesRefreshReadinessRequest$outboundSchema:
  z.ZodMiniType<
    ReceivingAddressesRefreshReadinessRequest$Outbound,
    ReceivingAddressesRefreshReadinessRequest
  > = z.pipe(
    z.object({
      idempotencyKey: z.string(),
      readinessId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        idempotencyKey: "Idempotency-Key",
        readinessId: "readiness_id",
      });
    }),
  );

export function receivingAddressesRefreshReadinessRequestToJSON(
  receivingAddressesRefreshReadinessRequest:
    ReceivingAddressesRefreshReadinessRequest,
): string {
  return JSON.stringify(
    ReceivingAddressesRefreshReadinessRequest$outboundSchema.parse(
      receivingAddressesRefreshReadinessRequest,
    ),
  );
}

/** @internal */
export const ReceivingAddressesRefreshReadinessResponse$inboundSchema:
  z.ZodMiniType<ReceivingAddressesRefreshReadinessResponse, unknown> = z.pipe(
    z.object({
      HttpMeta: models.HTTPMetadata$inboundSchema,
      ExternalReceivingAddress: types.optional(
        models.ExternalReceivingAddress$inboundSchema,
      ),
      ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "HttpMeta": "httpMeta",
        "ExternalReceivingAddress": "externalReceivingAddress",
        "ApiErrorEnvelope": "apiErrorEnvelope",
      });
    }),
  );

export function receivingAddressesRefreshReadinessResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ReceivingAddressesRefreshReadinessResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ReceivingAddressesRefreshReadinessResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ReceivingAddressesRefreshReadinessResponse' from JSON`,
  );
}
