/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9898f23c39c9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReceivingAddressesRegisterRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  body: models.ExternalReceivingAddressCreate;
};

export type ReceivingAddressesRegisterResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for register a receiving address.
   */
  externalReceivingAddress?: models.ExternalReceivingAddress | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ReceivingAddressesRegisterRequest$Outbound = {
  "Idempotency-Key": string;
  body: models.ExternalReceivingAddressCreate$Outbound;
};

/** @internal */
export const ReceivingAddressesRegisterRequest$outboundSchema: z.ZodMiniType<
  ReceivingAddressesRegisterRequest$Outbound,
  ReceivingAddressesRegisterRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    body: models.ExternalReceivingAddressCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function receivingAddressesRegisterRequestToJSON(
  receivingAddressesRegisterRequest: ReceivingAddressesRegisterRequest,
): string {
  return JSON.stringify(
    ReceivingAddressesRegisterRequest$outboundSchema.parse(
      receivingAddressesRegisterRequest,
    ),
  );
}

/** @internal */
export const ReceivingAddressesRegisterResponse$inboundSchema: z.ZodMiniType<
  ReceivingAddressesRegisterResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    ExternalReceivingAddress: types.optional(
      models.ExternalReceivingAddress$inboundSchema,
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ExternalReceivingAddress": "externalReceivingAddress",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function receivingAddressesRegisterResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReceivingAddressesRegisterResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ReceivingAddressesRegisterResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceivingAddressesRegisterResponse' from JSON`,
  );
}
