/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5076dd107165
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReceivingAddressesCreateControlChallengeRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  body: models.ExternalAddressControlChallengeCreate;
};

export type ReceivingAddressesCreateControlChallengeResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for create a receiving-address control challenge.
   */
  externalAddressControlChallenge?:
    | models.ExternalAddressControlChallenge
    | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ReceivingAddressesCreateControlChallengeRequest$Outbound = {
  "Idempotency-Key": string;
  body: models.ExternalAddressControlChallengeCreate$Outbound;
};

/** @internal */
export const ReceivingAddressesCreateControlChallengeRequest$outboundSchema:
  z.ZodMiniType<
    ReceivingAddressesCreateControlChallengeRequest$Outbound,
    ReceivingAddressesCreateControlChallengeRequest
  > = z.pipe(
    z.object({
      idempotencyKey: z.string(),
      body: models.ExternalAddressControlChallengeCreate$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        idempotencyKey: "Idempotency-Key",
      });
    }),
  );

export function receivingAddressesCreateControlChallengeRequestToJSON(
  receivingAddressesCreateControlChallengeRequest:
    ReceivingAddressesCreateControlChallengeRequest,
): string {
  return JSON.stringify(
    ReceivingAddressesCreateControlChallengeRequest$outboundSchema.parse(
      receivingAddressesCreateControlChallengeRequest,
    ),
  );
}

/** @internal */
export const ReceivingAddressesCreateControlChallengeResponse$inboundSchema:
  z.ZodMiniType<ReceivingAddressesCreateControlChallengeResponse, unknown> = z
    .pipe(
      z.object({
        HttpMeta: models.HTTPMetadata$inboundSchema,
        ExternalAddressControlChallenge: types.optional(
          models.ExternalAddressControlChallenge$inboundSchema,
        ),
        ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
      }),
      z.transform((v) => {
        return remap$(v, {
          "HttpMeta": "httpMeta",
          "ExternalAddressControlChallenge": "externalAddressControlChallenge",
          "ApiErrorEnvelope": "apiErrorEnvelope",
        });
      }),
    );

export function receivingAddressesCreateControlChallengeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ReceivingAddressesCreateControlChallengeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ReceivingAddressesCreateControlChallengeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ReceivingAddressesCreateControlChallengeResponse' from JSON`,
  );
}
