/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4ce3e7ea93dc
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReceivingAddressesActivateRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  readinessId: string;
};

export type ReceivingAddressesActivateResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for activate a receiving address.
   */
  externalReceivingAddress?: models.ExternalReceivingAddress | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ReceivingAddressesActivateRequest$Outbound = {
  "Idempotency-Key": string;
  readiness_id: string;
};

/** @internal */
export const ReceivingAddressesActivateRequest$outboundSchema: z.ZodMiniType<
  ReceivingAddressesActivateRequest$Outbound,
  ReceivingAddressesActivateRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    readinessId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
      readinessId: "readiness_id",
    });
  }),
);

export function receivingAddressesActivateRequestToJSON(
  receivingAddressesActivateRequest: ReceivingAddressesActivateRequest,
): string {
  return JSON.stringify(
    ReceivingAddressesActivateRequest$outboundSchema.parse(
      receivingAddressesActivateRequest,
    ),
  );
}

/** @internal */
export const ReceivingAddressesActivateResponse$inboundSchema: z.ZodMiniType<
  ReceivingAddressesActivateResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    ExternalReceivingAddress: types.optional(
      models.ExternalReceivingAddress$inboundSchema,
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ExternalReceivingAddress": "externalReceivingAddress",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function receivingAddressesActivateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReceivingAddressesActivateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ReceivingAddressesActivateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceivingAddressesActivateResponse' from JSON`,
  );
}
