/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ff0d1a04a550
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResourcesCreateRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  body: models.ResourceCreate;
};

export type ResourcesCreateResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for create a resource.
   */
  resource?: models.Resource | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ResourcesCreateRequest$Outbound = {
  "Idempotency-Key": string;
  body: models.ResourceCreate$Outbound;
};

/** @internal */
export const ResourcesCreateRequest$outboundSchema: z.ZodMiniType<
  ResourcesCreateRequest$Outbound,
  ResourcesCreateRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    body: models.ResourceCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function resourcesCreateRequestToJSON(
  resourcesCreateRequest: ResourcesCreateRequest,
): string {
  return JSON.stringify(
    ResourcesCreateRequest$outboundSchema.parse(resourcesCreateRequest),
  );
}

/** @internal */
export const ResourcesCreateResponse$inboundSchema: z.ZodMiniType<
  ResourcesCreateResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    Resource: types.optional(models.Resource$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Resource": "resource",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function resourcesCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResourcesCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourcesCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourcesCreateResponse' from JSON`,
  );
}
