/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 72f8e1268417
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResourcesCreateVersionRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  resourceId: string;
  body: models.ResourceVersionCreate;
};

export type ResourcesCreateVersionResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for create a resource version.
   */
  resourceVersion?: models.ResourceVersion | undefined;
  /**
   * The request failed.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ResourcesCreateVersionRequest$Outbound = {
  "Idempotency-Key": string;
  resource_id: string;
  body: models.ResourceVersionCreate$Outbound;
};

/** @internal */
export const ResourcesCreateVersionRequest$outboundSchema: z.ZodMiniType<
  ResourcesCreateVersionRequest$Outbound,
  ResourcesCreateVersionRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    resourceId: z.string(),
    body: models.ResourceVersionCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
      resourceId: "resource_id",
    });
  }),
);

export function resourcesCreateVersionRequestToJSON(
  resourcesCreateVersionRequest: ResourcesCreateVersionRequest,
): string {
  return JSON.stringify(
    ResourcesCreateVersionRequest$outboundSchema.parse(
      resourcesCreateVersionRequest,
    ),
  );
}

/** @internal */
export const ResourcesCreateVersionResponse$inboundSchema: z.ZodMiniType<
  ResourcesCreateVersionResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    ResourceVersion: types.optional(models.ResourceVersion$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ResourceVersion": "resourceVersion",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function resourcesCreateVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResourcesCreateVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourcesCreateVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourcesCreateVersionResponse' from JSON`,
  );
}
