/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 41391ba2ceff
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResourcesListRequest = {
  /**
   * Opaque pagination cursor from X-X402API-Next-Cursor or rel=next Link.
   */
  cursor?: string | undefined;
  /**
   * Number of results in the bounded array page (default and maximum 100).
   */
  pageSize?: number | undefined;
};

export type ResourcesListResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for list resources.
   */
  paginatedResourceList?: Array<models.Resource> | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ResourcesListRequest$Outbound = {
  cursor?: string | undefined;
  page_size: number;
};

/** @internal */
export const ResourcesListRequest$outboundSchema: z.ZodMiniType<
  ResourcesListRequest$Outbound,
  ResourcesListRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    pageSize: z._default(z.int(), 100),
  }),
  z.transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
    });
  }),
);

export function resourcesListRequestToJSON(
  resourcesListRequest: ResourcesListRequest,
): string {
  return JSON.stringify(
    ResourcesListRequest$outboundSchema.parse(resourcesListRequest),
  );
}

/** @internal */
export const ResourcesListResponse$inboundSchema: z.ZodMiniType<
  ResourcesListResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    PaginatedResourceList: types.optional(
      z.array(models.Resource$inboundSchema),
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PaginatedResourceList": "paginatedResourceList",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function resourcesListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResourcesListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourcesListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourcesListResponse' from JSON`,
  );
}
