/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1e4010a7e004
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResourcesListVersionsRequest = {
  /**
   * Opaque pagination cursor from X-X402API-Next-Cursor or rel=next Link.
   */
  cursor?: string | undefined;
  /**
   * Number of results in the bounded array page (default and maximum 100).
   */
  pageSize?: number | undefined;
  resourceId: string;
};

export type ResourcesListVersionsResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for list resource versions.
   */
  paginatedResourceVersionList?: Array<models.ResourceVersion> | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ResourcesListVersionsRequest$Outbound = {
  cursor?: string | undefined;
  page_size: number;
  resource_id: string;
};

/** @internal */
export const ResourcesListVersionsRequest$outboundSchema: z.ZodMiniType<
  ResourcesListVersionsRequest$Outbound,
  ResourcesListVersionsRequest
> = z.pipe(
  z.object({
    cursor: z.optional(z.string()),
    pageSize: z._default(z.int(), 100),
    resourceId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
      resourceId: "resource_id",
    });
  }),
);

export function resourcesListVersionsRequestToJSON(
  resourcesListVersionsRequest: ResourcesListVersionsRequest,
): string {
  return JSON.stringify(
    ResourcesListVersionsRequest$outboundSchema.parse(
      resourcesListVersionsRequest,
    ),
  );
}

/** @internal */
export const ResourcesListVersionsResponse$inboundSchema: z.ZodMiniType<
  ResourcesListVersionsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    PaginatedResourceVersionList: types.optional(
      z.array(models.ResourceVersion$inboundSchema),
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PaginatedResourceVersionList": "paginatedResourceVersionList",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function resourcesListVersionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResourcesListVersionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourcesListVersionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourcesListVersionsResponse' from JSON`,
  );
}
