/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e696a6e92ed9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResourcesActivateVersionRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  resourceId: string;
  versionId: string;
  body: models.ResourceVersionActivate;
};

export type ResourcesActivateVersionResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for activate a resource version.
   */
  resourceVersion?: models.ResourceVersion | undefined;
  /**
   * The request failed.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ResourcesActivateVersionRequest$Outbound = {
  "Idempotency-Key": string;
  resource_id: string;
  version_id: string;
  body: models.ResourceVersionActivate$Outbound;
};

/** @internal */
export const ResourcesActivateVersionRequest$outboundSchema: z.ZodMiniType<
  ResourcesActivateVersionRequest$Outbound,
  ResourcesActivateVersionRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    resourceId: z.string(),
    versionId: z.string(),
    body: models.ResourceVersionActivate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
      resourceId: "resource_id",
      versionId: "version_id",
    });
  }),
);

export function resourcesActivateVersionRequestToJSON(
  resourcesActivateVersionRequest: ResourcesActivateVersionRequest,
): string {
  return JSON.stringify(
    ResourcesActivateVersionRequest$outboundSchema.parse(
      resourcesActivateVersionRequest,
    ),
  );
}

/** @internal */
export const ResourcesActivateVersionResponse$inboundSchema: z.ZodMiniType<
  ResourcesActivateVersionResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    ResourceVersion: types.optional(models.ResourceVersion$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ResourceVersion": "resourceVersion",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function resourcesActivateVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResourcesActivateVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourcesActivateVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourcesActivateVersionResponse' from JSON`,
  );
}
