/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6bbc707da90a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResourcesRetireVersionRequest = {
  /**
   * Caller-persisted mutation key containing 8 to 160 safe ASCII characters. Replay the exact key and body after an uncertain outcome.
   */
  idempotencyKey: string;
  resourceId: string;
  versionId: string;
  body: models.ResourceVersionRetire;
};

export type ResourcesRetireVersionResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for retire a resource version.
   */
  resourceVersion?: models.ResourceVersion | undefined;
  /**
   * The request failed.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export type ResourcesRetireVersionRequest$Outbound = {
  "Idempotency-Key": string;
  resource_id: string;
  version_id: string;
  body: models.ResourceVersionRetire$Outbound;
};

/** @internal */
export const ResourcesRetireVersionRequest$outboundSchema: z.ZodMiniType<
  ResourcesRetireVersionRequest$Outbound,
  ResourcesRetireVersionRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.string(),
    resourceId: z.string(),
    versionId: z.string(),
    body: models.ResourceVersionRetire$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
      resourceId: "resource_id",
      versionId: "version_id",
    });
  }),
);

export function resourcesRetireVersionRequestToJSON(
  resourcesRetireVersionRequest: ResourcesRetireVersionRequest,
): string {
  return JSON.stringify(
    ResourcesRetireVersionRequest$outboundSchema.parse(
      resourcesRetireVersionRequest,
    ),
  );
}

/** @internal */
export const ResourcesRetireVersionResponse$inboundSchema: z.ZodMiniType<
  ResourcesRetireVersionResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    ResourceVersion: types.optional(models.ResourceVersion$inboundSchema),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ResourceVersion": "resourceVersion",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function resourcesRetireVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResourcesRetireVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourcesRetireVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourcesRetireVersionResponse' from JSON`,
  );
}
