/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 97cb92c7caaf
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const Finality = {
  Confirmed: "confirmed",
  Finalized: "finalized",
  Latest: "latest",
} as const;
export type Finality = ClosedEnum<typeof Finality>;

export type WalletsRetrieveBalanceRequest = {
  finality?: Finality | undefined;
  id: string;
};

export type WalletsRetrieveBalanceResponse = {
  httpMeta: models.HTTPMetadata;
  /**
   * Successful response for retrieve wallet balances.
   */
  walletBalanceResponse?: models.WalletBalanceResponse | undefined;
  /**
   * The request failed with a stable machine-readable error.
   */
  apiErrorEnvelope?: models.ApiErrorEnvelope | undefined;
};

/** @internal */
export const Finality$outboundSchema: z.ZodMiniEnum<typeof Finality> = z.enum(
  Finality,
);

/** @internal */
export type WalletsRetrieveBalanceRequest$Outbound = {
  finality: string;
  id: string;
};

/** @internal */
export const WalletsRetrieveBalanceRequest$outboundSchema: z.ZodMiniType<
  WalletsRetrieveBalanceRequest$Outbound,
  WalletsRetrieveBalanceRequest
> = z.object({
  finality: z._default(Finality$outboundSchema, "finalized"),
  id: z.string(),
});

export function walletsRetrieveBalanceRequestToJSON(
  walletsRetrieveBalanceRequest: WalletsRetrieveBalanceRequest,
): string {
  return JSON.stringify(
    WalletsRetrieveBalanceRequest$outboundSchema.parse(
      walletsRetrieveBalanceRequest,
    ),
  );
}

/** @internal */
export const WalletsRetrieveBalanceResponse$inboundSchema: z.ZodMiniType<
  WalletsRetrieveBalanceResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: models.HTTPMetadata$inboundSchema,
    WalletBalanceResponse: types.optional(
      models.WalletBalanceResponse$inboundSchema,
    ),
    ApiErrorEnvelope: types.optional(models.ApiErrorEnvelope$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "WalletBalanceResponse": "walletBalanceResponse",
      "ApiErrorEnvelope": "apiErrorEnvelope",
    });
  }),
);

export function walletsRetrieveBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletsRetrieveBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletsRetrieveBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletsRetrieveBalanceResponse' from JSON`,
  );
}
