/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1f7b1c091e2a
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiError = {
  /**
   * HTTP response status.
   */
  status: number;
  /**
   * Stable machine-readable error code.
   */
  code: string;
  /**
   * Human-readable text or structured field validation details.
   */
  detail: any | null;
};

/** @internal */
export const ApiError$inboundSchema: z.ZodMiniType<ApiError, unknown> = z
  .object({
    status: types.number(),
    code: types.string(),
    detail: types.nullable(z.any()),
  });

export function apiErrorFromJSON(
  jsonString: string,
): SafeParseResult<ApiError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiError' from JSON`,
  );
}
