/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1f3a9651d68d
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { ApiError, ApiError$inboundSchema } from "./api-error.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiErrorEnvelope = {
  error: ApiError;
};

/** @internal */
export const ApiErrorEnvelope$inboundSchema: z.ZodMiniType<
  ApiErrorEnvelope,
  unknown
> = z.object({
  error: ApiError$inboundSchema,
});

export function apiErrorEnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<ApiErrorEnvelope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiErrorEnvelope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiErrorEnvelope' from JSON`,
  );
}
