/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a9b926811abf
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ObservationBlock,
  ObservationBlock$inboundSchema,
} from "./observation-block.js";

export type BalanceAsset = {
  assetId: string;
  displayName: string;
  symbol: string;
  contractAddress: string;
  decimals: number;
  amountAtomic: string;
  amount: string;
  issuerNative: boolean;
  observedAt: Date;
  nodeSource: string;
  sourceConsensus: string;
  block: ObservationBlock;
};

/** @internal */
export const BalanceAsset$inboundSchema: z.ZodMiniType<BalanceAsset, unknown> =
  z.pipe(
    z.object({
      asset_id: types.string(),
      display_name: types.string(),
      symbol: types.string(),
      contract_address: types.string(),
      decimals: types.number(),
      amount_atomic: types.string(),
      amount: types.string(),
      issuer_native: types.boolean(),
      observed_at: types.date(),
      node_source: types.string(),
      source_consensus: types.string(),
      block: ObservationBlock$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "asset_id": "assetId",
        "display_name": "displayName",
        "contract_address": "contractAddress",
        "amount_atomic": "amountAtomic",
        "issuer_native": "issuerNative",
        "observed_at": "observedAt",
        "node_source": "nodeSource",
        "source_consensus": "sourceConsensus",
      });
    }),
  );

export function balanceAssetFromJSON(
  jsonString: string,
): SafeParseResult<BalanceAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BalanceAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BalanceAsset' from JSON`,
  );
}
