/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c96e488f52f7
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaymentReadinessBlocker,
  PaymentReadinessBlocker$inboundSchema,
} from "./payment-readiness-blocker.js";

/**
 * * `ready` - ready
 *
 * @remarks
 * * `needs_wallet` - needs_wallet
 * * `paused_by_tenant` - paused_by_tenant
 * * `temporarily_unavailable` - temporarily_unavailable
 * * `not_selected` - not_selected
 */
export const CanonicalPaymentReadinessRailStatus = {
  Ready: "ready",
  NeedsWallet: "needs_wallet",
  PausedByTenant: "paused_by_tenant",
  TemporarilyUnavailable: "temporarily_unavailable",
  NotSelected: "not_selected",
} as const;
/**
 * * `ready` - ready
 *
 * @remarks
 * * `needs_wallet` - needs_wallet
 * * `paused_by_tenant` - paused_by_tenant
 * * `temporarily_unavailable` - temporarily_unavailable
 * * `not_selected` - not_selected
 */
export type CanonicalPaymentReadinessRailStatus = OpenEnum<
  typeof CanonicalPaymentReadinessRailStatus
>;

export type CanonicalPaymentReadinessRail = {
  assetId: string;
  network: string;
  symbol: string;
  selected: boolean;
  walletReady: boolean;
  platformAvailable: boolean;
  acceptingNewPayments: boolean;
  status: CanonicalPaymentReadinessRailStatus;
  blockers: Array<PaymentReadinessBlocker>;
};

/** @internal */
export const CanonicalPaymentReadinessRailStatus$inboundSchema: z.ZodMiniType<
  CanonicalPaymentReadinessRailStatus,
  unknown
> = openEnums.inboundSchema(CanonicalPaymentReadinessRailStatus);

/** @internal */
export const CanonicalPaymentReadinessRail$inboundSchema: z.ZodMiniType<
  CanonicalPaymentReadinessRail,
  unknown
> = z.pipe(
  z.object({
    asset_id: types.string(),
    network: types.string(),
    symbol: types.string(),
    selected: types.boolean(),
    wallet_ready: types.boolean(),
    platform_available: types.boolean(),
    accepting_new_payments: types.boolean(),
    status: CanonicalPaymentReadinessRailStatus$inboundSchema,
    blockers: z.array(PaymentReadinessBlocker$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "wallet_ready": "walletReady",
      "platform_available": "platformAvailable",
      "accepting_new_payments": "acceptingNewPayments",
    });
  }),
);

export function canonicalPaymentReadinessRailFromJSON(
  jsonString: string,
): SafeParseResult<CanonicalPaymentReadinessRail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CanonicalPaymentReadinessRail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CanonicalPaymentReadinessRail' from JSON`,
  );
}
