/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DynamicChargePaymentResponse = {
  chargeId: string;
  orderId: string;
  /**
   * Durable settlement identifier used by payment and receipt APIs.
   */
  paymentId: string;
  state: string;
  confirmed?: boolean | undefined;
  finalized?: boolean | undefined;
  payer: string;
  transaction: string;
  network: string;
  errorReason: string;
};

/** @internal */
export const DynamicChargePaymentResponse$inboundSchema: z.ZodMiniType<
  DynamicChargePaymentResponse,
  unknown
> = z.pipe(
  z.object({
    charge_id: types.string(),
    order_id: types.string(),
    payment_id: types.string(),
    state: types.string(),
    confirmed: types.optional(types.boolean()),
    finalized: types.optional(types.boolean()),
    payer: types.string(),
    transaction: types.string(),
    network: types.string(),
    error_reason: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "charge_id": "chargeId",
      "order_id": "orderId",
      "payment_id": "paymentId",
      "error_reason": "errorReason",
    });
  }),
);

export function dynamicChargePaymentResponseFromJSON(
  jsonString: string,
): SafeParseResult<DynamicChargePaymentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DynamicChargePaymentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DynamicChargePaymentResponse' from JSON`,
  );
}
