/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a512c94fb972
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DynamicChargePrice,
  DynamicChargePrice$inboundSchema,
} from "./dynamic-charge-price.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FeePolicyDocument,
  FeePolicyDocument$inboundSchema,
} from "./fee-policy-document.js";
import {
  NetworkFeeAlternative,
  NetworkFeeAlternative$inboundSchema,
} from "./network-fee-alternative.js";

export type DynamicChargeResponse = {
  chargeId: string;
  chargeDigest: string;
  orderId: string;
  status: string;
  resourceVersionId: string;
  paymentIdentifier: string;
  expiresAt: Date;
  createdAt: Date;
  prices: Array<DynamicChargePrice>;
  requestedExpiresInSeconds: number;
  /**
   * Tenant application metadata frozen into the charge digest. Maximum canonical size is 16 KiB; floating-point numbers are not accepted.
   */
  metadata: { [k: string]: any };
  metadataDigest: string;
  paymentRequired: any;
  paymentRequiredHeader: string;
  eligibleAlternatives: Array<NetworkFeeAlternative>;
  feePolicy: FeePolicyDocument;
  feeQuoteDigest: string;
};

/** @internal */
export const DynamicChargeResponse$inboundSchema: z.ZodMiniType<
  DynamicChargeResponse,
  unknown
> = z.pipe(
  z.object({
    charge_id: types.string(),
    charge_digest: types.string(),
    order_id: types.string(),
    status: types.string(),
    resource_version_id: types.string(),
    payment_identifier: types.string(),
    expires_at: types.date(),
    created_at: types.date(),
    prices: z.array(DynamicChargePrice$inboundSchema),
    requested_expires_in_seconds: types.number(),
    metadata: z.record(z.string(), z.any()),
    metadata_digest: types.string(),
    payment_required: z.any(),
    payment_required_header: types.string(),
    eligible_alternatives: z.array(NetworkFeeAlternative$inboundSchema),
    fee_policy: FeePolicyDocument$inboundSchema,
    fee_quote_digest: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "charge_id": "chargeId",
      "charge_digest": "chargeDigest",
      "order_id": "orderId",
      "resource_version_id": "resourceVersionId",
      "payment_identifier": "paymentIdentifier",
      "expires_at": "expiresAt",
      "created_at": "createdAt",
      "requested_expires_in_seconds": "requestedExpiresInSeconds",
      "metadata_digest": "metadataDigest",
      "payment_required": "paymentRequired",
      "payment_required_header": "paymentRequiredHeader",
      "eligible_alternatives": "eligibleAlternatives",
      "fee_policy": "feePolicy",
      "fee_quote_digest": "feeQuoteDigest",
    });
  }),
);

export function dynamicChargeResponseFromJSON(
  jsonString: string,
): SafeParseResult<DynamicChargeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DynamicChargeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DynamicChargeResponse' from JSON`,
  );
}
