/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 77dc76ca6372
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  DynamicChargePrice,
  DynamicChargePrice$Outbound,
  DynamicChargePrice$outboundSchema,
} from "./dynamic-charge-price.js";
import {
  FeePolicyModeInputEnum,
  FeePolicyModeInputEnum$outboundSchema,
} from "./fee-policy-mode-input-enum.js";
import {
  FeePolicyQuoteCurrencyInputEnum,
  FeePolicyQuoteCurrencyInputEnum$outboundSchema,
} from "./fee-policy-quote-currency-input-enum.js";

/**
 * * `GET` - GET
 *
 * @remarks
 * * `POST` - POST
 * * `PUT` - PUT
 * * `PATCH` - PATCH
 * * `DELETE` - DELETE
 */
export const Method = {
  Get: "GET",
  Post: "POST",
  Put: "PUT",
  Patch: "PATCH",
  Delete: "DELETE",
} as const;
/**
 * * `GET` - GET
 *
 * @remarks
 * * `POST` - POST
 * * `PUT` - PUT
 * * `PATCH` - PATCH
 * * `DELETE` - DELETE
 */
export type Method = ClosedEnum<typeof Method>;

export type DynamicChargeCreate = {
  resourceVersionId: string;
  method?: Method | undefined;
  resourceUrl: string;
  bodyBase64?: string | undefined;
  contentType?: string | null | undefined;
  description?: string | undefined;
  prices: Array<DynamicChargePrice>;
  /**
   * * `buyer_pays` - buyer_pays
   *
   * @remarks
   * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
   */
  feeMode?: FeePolicyModeInputEnum | undefined;
  /**
   * * `USD` - USD
   */
  quoteCurrency?: FeePolicyQuoteCurrencyInputEnum | undefined;
  feeAllowanceCapQuoteMicros?: string | undefined;
  expiresInSeconds: number;
  /**
   * Tenant application metadata frozen into the charge digest. Maximum canonical size is 16 KiB; floating-point numbers are not accepted.
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const Method$outboundSchema: z.ZodMiniEnum<typeof Method> = z.enum(
  Method,
);

/** @internal */
export type DynamicChargeCreate$Outbound = {
  resource_version_id: string;
  method: string;
  resource_url: string;
  body_base64: string;
  content_type?: string | null | undefined;
  description?: string | undefined;
  prices: Array<DynamicChargePrice$Outbound>;
  fee_mode?: string | undefined;
  quote_currency?: string | undefined;
  fee_allowance_cap_quote_micros?: string | undefined;
  expires_in_seconds: number;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const DynamicChargeCreate$outboundSchema: z.ZodMiniType<
  DynamicChargeCreate$Outbound,
  DynamicChargeCreate
> = z.pipe(
  z.object({
    resourceVersionId: z.string(),
    method: z._default(Method$outboundSchema, "POST"),
    resourceUrl: z.string(),
    bodyBase64: z._default(z.string(), ""),
    contentType: z.optional(z.nullable(z.string())),
    description: z.optional(z.string()),
    prices: z.array(DynamicChargePrice$outboundSchema),
    feeMode: z.optional(FeePolicyModeInputEnum$outboundSchema),
    quoteCurrency: z.optional(FeePolicyQuoteCurrencyInputEnum$outboundSchema),
    feeAllowanceCapQuoteMicros: z.optional(z.string()),
    expiresInSeconds: z.int(),
    metadata: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      resourceVersionId: "resource_version_id",
      resourceUrl: "resource_url",
      bodyBase64: "body_base64",
      contentType: "content_type",
      feeMode: "fee_mode",
      quoteCurrency: "quote_currency",
      feeAllowanceCapQuoteMicros: "fee_allowance_cap_quote_micros",
      expiresInSeconds: "expires_in_seconds",
    });
  }),
);

export function dynamicChargeCreateToJSON(
  dynamicChargeCreate: DynamicChargeCreate,
): string {
  return JSON.stringify(
    DynamicChargeCreate$outboundSchema.parse(dynamicChargeCreate),
  );
}
