/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DynamicChargePrice,
  DynamicChargePrice$inboundSchema,
} from "./dynamic-charge-price.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PublicFeePolicyDocument,
  PublicFeePolicyDocument$inboundSchema,
} from "./public-fee-policy-document.js";
import {
  PublicNetworkFeeAlternative,
  PublicNetworkFeeAlternative$inboundSchema,
} from "./public-network-fee-alternative.js";

export type DynamicChargeResponse = {
  /**
   * Immutable challenge UUID created for this charge.
   */
  chargeId: string;
  chargeDigest: string;
  orderId: string;
  /**
   * Current projected order status; payment terms remain immutable.
   */
  status: string;
  resourceVersionId: string;
  /**
   * Opaque server challenge handle. Return it to the buyer as X-X402API-Challenge-Handle; it is not the buyer payment identifier.
   */
  paymentIdentifier: string;
  expiresAt: Date;
  /**
   * Optional HTTPS hosted checkout for this exact charge. It is a short-lived bearer capability and expires with expires_at.
   */
  humanCheckoutUrl?: string | undefined;
  /**
   * Optional canonical hosted-checkout URL to encode as a QR; never a recipient address.
   */
  qrPayload?: string | undefined;
  createdAt: Date;
  prices: Array<DynamicChargePrice>;
  requestedExpiresInSeconds: number;
  /**
   * Tenant application metadata frozen into the charge digest. Maximum canonical size is 16 KiB; floating-point numbers are not accepted.
   */
  metadata: { [k: string]: any };
  metadataDigest: string;
  /**
   * Complete immutable x402 v2 PAYMENT-REQUIRED document.
   */
  paymentRequired: any;
  /**
   * Canonical base64-encoded value to return in the buyer-facing PAYMENT-REQUIRED header.
   */
  paymentRequiredHeader: string;
  eligibleAlternatives: Array<PublicNetworkFeeAlternative>;
  feePolicy: PublicFeePolicyDocument;
  feeQuoteDigest: string;
};

/** @internal */
export const DynamicChargeResponse$inboundSchema: z.ZodMiniType<
  DynamicChargeResponse,
  unknown
> = z.pipe(
  z.object({
    charge_id: types.string(),
    charge_digest: types.string(),
    order_id: types.string(),
    status: types.string(),
    resource_version_id: types.string(),
    payment_identifier: types.string(),
    expires_at: types.date(),
    human_checkout_url: types.optional(types.string()),
    qr_payload: types.optional(types.string()),
    created_at: types.date(),
    prices: z.array(DynamicChargePrice$inboundSchema),
    requested_expires_in_seconds: types.number(),
    metadata: z.record(z.string(), z.any()),
    metadata_digest: types.string(),
    payment_required: z.any(),
    payment_required_header: types.string(),
    eligible_alternatives: z.array(PublicNetworkFeeAlternative$inboundSchema),
    fee_policy: PublicFeePolicyDocument$inboundSchema,
    fee_quote_digest: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "charge_id": "chargeId",
      "charge_digest": "chargeDigest",
      "order_id": "orderId",
      "resource_version_id": "resourceVersionId",
      "payment_identifier": "paymentIdentifier",
      "expires_at": "expiresAt",
      "human_checkout_url": "humanCheckoutUrl",
      "qr_payload": "qrPayload",
      "created_at": "createdAt",
      "requested_expires_in_seconds": "requestedExpiresInSeconds",
      "metadata_digest": "metadataDigest",
      "payment_required": "paymentRequired",
      "payment_required_header": "paymentRequiredHeader",
      "eligible_alternatives": "eligibleAlternatives",
      "fee_policy": "feePolicy",
      "fee_quote_digest": "feeQuoteDigest",
    });
  }),
);

export function dynamicChargeResponseFromJSON(
  jsonString: string,
): SafeParseResult<DynamicChargeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DynamicChargeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DynamicChargeResponse' from JSON`,
  );
}
