/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 624735b6b287
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DynamicChargePrice = {
  assetId: string;
  amountAtomic: string;
};

/** @internal */
export const DynamicChargePrice$inboundSchema: z.ZodMiniType<
  DynamicChargePrice,
  unknown
> = z.pipe(
  z.object({
    asset_id: types.string(),
    amount_atomic: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "amount_atomic": "amountAtomic",
    });
  }),
);
/** @internal */
export type DynamicChargePrice$Outbound = {
  asset_id: string;
  amount_atomic: string;
};

/** @internal */
export const DynamicChargePrice$outboundSchema: z.ZodMiniType<
  DynamicChargePrice$Outbound,
  DynamicChargePrice
> = z.pipe(
  z.object({
    assetId: z.string(),
    amountAtomic: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      assetId: "asset_id",
      amountAtomic: "amount_atomic",
    });
  }),
);

export function dynamicChargePriceToJSON(
  dynamicChargePrice: DynamicChargePrice,
): string {
  return JSON.stringify(
    DynamicChargePrice$outboundSchema.parse(dynamicChargePrice),
  );
}
export function dynamicChargePriceFromJSON(
  jsonString: string,
): SafeParseResult<DynamicChargePrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DynamicChargePrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DynamicChargePrice' from JSON`,
  );
}
