/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 881dd5778a56
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ExternalAddressProofInputMethodEnum,
  ExternalAddressProofInputMethodEnum$inboundSchema,
} from "./external-address-proof-input-method-enum.js";

export type ExternalAddressControlCapability = {
  network: string;
  proofMethods: Array<ExternalAddressProofInputMethodEnum>;
};

/** @internal */
export const ExternalAddressControlCapability$inboundSchema: z.ZodMiniType<
  ExternalAddressControlCapability,
  unknown
> = z.pipe(
  z.object({
    network: types.string(),
    proof_methods: z.array(ExternalAddressProofInputMethodEnum$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "proof_methods": "proofMethods",
    });
  }),
);

export function externalAddressControlCapabilityFromJSON(
  jsonString: string,
): SafeParseResult<ExternalAddressControlCapability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExternalAddressControlCapability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalAddressControlCapability' from JSON`,
  );
}
