/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b05cd50daead
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * * `signed_message` - signed_message
 *
 * @remarks
 * * `onchain_canary` - onchain_canary
 */
export const ProofMethodExternalAddressProofInputMethodEnum = {
  SignedMessage: "signed_message",
  OnchainCanary: "onchain_canary",
} as const;
/**
 * * `signed_message` - signed_message
 *
 * @remarks
 * * `onchain_canary` - onchain_canary
 */
export type ProofMethodExternalAddressProofInputMethodEnum = OpenEnum<
  typeof ProofMethodExternalAddressProofInputMethodEnum
>;

export type ExternalReceivingAddressProofMethod =
  | ProofMethodExternalAddressProofInputMethodEnum
  | any;

/**
 * * `current` - current
 *
 * @remarks
 * * `refresh_required` - refresh_required
 * * `durable` - durable
 * * `activation_required` - activation_required
 * * `inactive` - inactive
 */
export const ReadinessStatus = {
  Current: "current",
  RefreshRequired: "refresh_required",
  Durable: "durable",
  ActivationRequired: "activation_required",
  Inactive: "inactive",
} as const;
/**
 * * `current` - current
 *
 * @remarks
 * * `refresh_required` - refresh_required
 * * `durable` - durable
 * * `activation_required` - activation_required
 * * `inactive` - inactive
 */
export type ReadinessStatus = OpenEnum<typeof ReadinessStatus>;

export type ExternalReceivingAddress = {
  id: string;
  walletId: string;
  walletVersionId: string;
  label: string;
  network: string;
  assetId: string;
  address: string;
  status: string;
  proofMethod: ProofMethodExternalAddressProofInputMethodEnum | any | null;
  proofVerifiedAt: Date | null;
  readinessState: string;
  readinessUsable: boolean;
  readinessRefreshEligible: boolean;
  readinessStatus: ReadinessStatus;
  activationEligible: boolean;
  activationEligibleAt: Date;
  verifiedAt: Date;
  expiresAt: Date;
  activatedAt: Date | null;
  observedBalanceAtomic: string | null;
  createdAt: Date;
};

/** @internal */
export const ProofMethodExternalAddressProofInputMethodEnum$inboundSchema:
  z.ZodMiniType<ProofMethodExternalAddressProofInputMethodEnum, unknown> =
    openEnums.inboundSchema(ProofMethodExternalAddressProofInputMethodEnum);

/** @internal */
export const ExternalReceivingAddressProofMethod$inboundSchema: z.ZodMiniType<
  ExternalReceivingAddressProofMethod,
  unknown
> = smartUnion([
  ProofMethodExternalAddressProofInputMethodEnum$inboundSchema,
  z.any(),
]);

export function externalReceivingAddressProofMethodFromJSON(
  jsonString: string,
): SafeParseResult<ExternalReceivingAddressProofMethod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExternalReceivingAddressProofMethod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalReceivingAddressProofMethod' from JSON`,
  );
}

/** @internal */
export const ReadinessStatus$inboundSchema: z.ZodMiniType<
  ReadinessStatus,
  unknown
> = openEnums.inboundSchema(ReadinessStatus);

/** @internal */
export const ExternalReceivingAddress$inboundSchema: z.ZodMiniType<
  ExternalReceivingAddress,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    wallet_id: types.string(),
    wallet_version_id: types.string(),
    label: types.string(),
    network: types.string(),
    asset_id: types.string(),
    address: types.string(),
    status: types.string(),
    proof_method: types.nullable(
      smartUnion([
        ProofMethodExternalAddressProofInputMethodEnum$inboundSchema,
        z.any(),
      ]),
    ),
    proof_verified_at: types.nullable(types.date()),
    readiness_state: types.string(),
    readiness_usable: types.boolean(),
    readiness_refresh_eligible: types.boolean(),
    readiness_status: ReadinessStatus$inboundSchema,
    activation_eligible: types.boolean(),
    activation_eligible_at: types.date(),
    verified_at: types.date(),
    expires_at: types.date(),
    activated_at: types.nullable(types.date()),
    observed_balance_atomic: types.nullable(types.string()),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "wallet_id": "walletId",
      "wallet_version_id": "walletVersionId",
      "asset_id": "assetId",
      "proof_method": "proofMethod",
      "proof_verified_at": "proofVerifiedAt",
      "readiness_state": "readinessState",
      "readiness_usable": "readinessUsable",
      "readiness_refresh_eligible": "readinessRefreshEligible",
      "readiness_status": "readinessStatus",
      "activation_eligible": "activationEligible",
      "activation_eligible_at": "activationEligibleAt",
      "verified_at": "verifiedAt",
      "expires_at": "expiresAt",
      "activated_at": "activatedAt",
      "observed_balance_atomic": "observedBalanceAtomic",
      "created_at": "createdAt",
    });
  }),
);

export function externalReceivingAddressFromJSON(
  jsonString: string,
): SafeParseResult<ExternalReceivingAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExternalReceivingAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalReceivingAddress' from JSON`,
  );
}
