/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4f60c8cf3ab2
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ExternalAddressProofInputMethodEnum,
  ExternalAddressProofInputMethodEnum$outboundSchema,
} from "./external-address-proof-input-method-enum.js";

/**
 * Reject extra or missing JSON keys instead of silently projecting them.
 */
export type ExternalAddressControlProofInput = {
  /**
   * * `signed_message` - signed_message
   *
   * @remarks
   * * `onchain_canary` - onchain_canary
   */
  method: ExternalAddressProofInputMethodEnum;
  signature?: string | undefined;
  transactionHash?: string | undefined;
};

/** @internal */
export type ExternalAddressControlProofInput$Outbound = {
  method: string;
  signature?: string | undefined;
  transaction_hash?: string | undefined;
};

/** @internal */
export const ExternalAddressControlProofInput$outboundSchema: z.ZodMiniType<
  ExternalAddressControlProofInput$Outbound,
  ExternalAddressControlProofInput
> = z.pipe(
  z.object({
    method: ExternalAddressProofInputMethodEnum$outboundSchema,
    signature: z.optional(z.string()),
    transactionHash: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      transactionHash: "transaction_hash",
    });
  }),
);

export function externalAddressControlProofInputToJSON(
  externalAddressControlProofInput: ExternalAddressControlProofInput,
): string {
  return JSON.stringify(
    ExternalAddressControlProofInput$outboundSchema.parse(
      externalAddressControlProofInput,
    ),
  );
}
