/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 416c29065b66
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ExternalAddressProofInputMethodEnum,
  ExternalAddressProofInputMethodEnum$outboundSchema,
} from "./external-address-proof-input-method-enum.js";

/**
 * Reject extra or missing JSON keys instead of silently projecting them.
 */
export type ExternalAddressControlChallengeCreate = {
  network: string;
  assetId: string;
  address: string;
  /**
   * * `signed_message` - signed_message
   *
   * @remarks
   * * `onchain_canary` - onchain_canary
   */
  proofMethod: ExternalAddressProofInputMethodEnum;
};

/** @internal */
export type ExternalAddressControlChallengeCreate$Outbound = {
  network: string;
  asset_id: string;
  address: string;
  proof_method: string;
};

/** @internal */
export const ExternalAddressControlChallengeCreate$outboundSchema:
  z.ZodMiniType<
    ExternalAddressControlChallengeCreate$Outbound,
    ExternalAddressControlChallengeCreate
  > = z.pipe(
    z.object({
      network: z.string(),
      assetId: z.string(),
      address: z.string(),
      proofMethod: ExternalAddressProofInputMethodEnum$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        assetId: "asset_id",
        proofMethod: "proof_method",
      });
    }),
  );

export function externalAddressControlChallengeCreateToJSON(
  externalAddressControlChallengeCreate: ExternalAddressControlChallengeCreate,
): string {
  return JSON.stringify(
    ExternalAddressControlChallengeCreate$outboundSchema.parse(
      externalAddressControlChallengeCreate,
    ),
  );
}
