/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 43712f2a9f94
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ExternalAddressControlProofInput,
  ExternalAddressControlProofInput$Outbound,
  ExternalAddressControlProofInput$outboundSchema,
} from "./external-address-control-proof-input.js";

/**
 * Reject extra or missing JSON keys instead of silently projecting them.
 */
export type ExternalReceivingAddressRotation = {
  challengeId: string;
  /**
   * Reject extra or missing JSON keys instead of silently projecting them.
   */
  proof: ExternalAddressControlProofInput;
  reason: string;
};

/** @internal */
export type ExternalReceivingAddressRotation$Outbound = {
  challenge_id: string;
  proof: ExternalAddressControlProofInput$Outbound;
  reason: string;
};

/** @internal */
export const ExternalReceivingAddressRotation$outboundSchema: z.ZodMiniType<
  ExternalReceivingAddressRotation$Outbound,
  ExternalReceivingAddressRotation
> = z.pipe(
  z.object({
    challengeId: z.string(),
    proof: ExternalAddressControlProofInput$outboundSchema,
    reason: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      challengeId: "challenge_id",
    });
  }),
);

export function externalReceivingAddressRotationToJSON(
  externalReceivingAddressRotation: ExternalReceivingAddressRotation,
): string {
  return JSON.stringify(
    ExternalReceivingAddressRotation$outboundSchema.parse(
      externalReceivingAddressRotation,
    ),
  );
}
