/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 23222931e3a6
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ExternalAddressControlProofInput,
  ExternalAddressControlProofInput$Outbound,
  ExternalAddressControlProofInput$outboundSchema,
} from "./external-address-control-proof-input.js";

/**
 * Reject extra or missing JSON keys instead of silently projecting them.
 */
export type ExternalReceivingAddressCreate = {
  label: string;
  challengeId: string;
  /**
   * Reject extra or missing JSON keys instead of silently projecting them.
   */
  proof: ExternalAddressControlProofInput;
};

/** @internal */
export type ExternalReceivingAddressCreate$Outbound = {
  label: string;
  challenge_id: string;
  proof: ExternalAddressControlProofInput$Outbound;
};

/** @internal */
export const ExternalReceivingAddressCreate$outboundSchema: z.ZodMiniType<
  ExternalReceivingAddressCreate$Outbound,
  ExternalReceivingAddressCreate
> = z.pipe(
  z.object({
    label: z.string(),
    challengeId: z.string(),
    proof: ExternalAddressControlProofInput$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      challengeId: "challenge_id",
    });
  }),
);

export function externalReceivingAddressCreateToJSON(
  externalReceivingAddressCreate: ExternalReceivingAddressCreate,
): string {
  return JSON.stringify(
    ExternalReceivingAddressCreate$outboundSchema.parse(
      externalReceivingAddressCreate,
    ),
  );
}
