/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 29c18d91f236
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `signed_message` - signed_message
 *
 * @remarks
 * * `onchain_canary` - onchain_canary
 */
export const ExternalAddressProofInputMethodEnum = {
  SignedMessage: "signed_message",
  OnchainCanary: "onchain_canary",
} as const;
/**
 * * `signed_message` - signed_message
 *
 * @remarks
 * * `onchain_canary` - onchain_canary
 */
export type ExternalAddressProofInputMethodEnum = OpenEnum<
  typeof ExternalAddressProofInputMethodEnum
>;

/** @internal */
export const ExternalAddressProofInputMethodEnum$inboundSchema: z.ZodMiniType<
  ExternalAddressProofInputMethodEnum,
  unknown
> = openEnums.inboundSchema(ExternalAddressProofInputMethodEnum);
/** @internal */
export const ExternalAddressProofInputMethodEnum$outboundSchema: z.ZodMiniType<
  string,
  ExternalAddressProofInputMethodEnum
> = openEnums.outboundSchema(ExternalAddressProofInputMethodEnum);
