/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 00a382c7c1f9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * * `signed_message` - Signed message
 *
 * @remarks
 * * `onchain_canary` - On-chain canary
 */
export const ProofMethod = {
  SignedMessage: "signed_message",
  OnchainCanary: "onchain_canary",
} as const;
/**
 * * `signed_message` - Signed message
 *
 * @remarks
 * * `onchain_canary` - On-chain canary
 */
export type ProofMethod = OpenEnum<typeof ProofMethod>;

export type ExternalAddressControlChallenge = {
  id: string;
  network: string;
  assetId: string;
  addressDisplay: string;
  proofMethod: ProofMethod;
  message: string;
  challengeDigest: string;
  canaryInstructions: any | null;
  expiresAt: Date;
  consumedAt: Date | null;
  createdAt: Date;
};

/** @internal */
export const ProofMethod$inboundSchema: z.ZodMiniType<ProofMethod, unknown> =
  openEnums.inboundSchema(ProofMethod);

/** @internal */
export const ExternalAddressControlChallenge$inboundSchema: z.ZodMiniType<
  ExternalAddressControlChallenge,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    network: types.string(),
    asset_id: types.string(),
    address_display: types.string(),
    proof_method: ProofMethod$inboundSchema,
    message: types.string(),
    challenge_digest: types.string(),
    canary_instructions: types.nullable(z.any()),
    expires_at: types.date(),
    consumed_at: types.nullable(types.date()),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "address_display": "addressDisplay",
      "proof_method": "proofMethod",
      "challenge_digest": "challengeDigest",
      "canary_instructions": "canaryInstructions",
      "expires_at": "expiresAt",
      "consumed_at": "consumedAt",
      "created_at": "createdAt",
    });
  }),
);

export function externalAddressControlChallengeFromJSON(
  jsonString: string,
): SafeParseResult<ExternalAddressControlChallenge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExternalAddressControlChallenge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalAddressControlChallenge' from JSON`,
  );
}
