/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 098f55ee9ff5
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ExternalAddressControlCapability,
  ExternalAddressControlCapability$inboundSchema,
} from "./external-address-control-capability.js";

export type ExternalAddressControlCapabilities = {
  networks: Array<ExternalAddressControlCapability>;
};

/** @internal */
export const ExternalAddressControlCapabilities$inboundSchema: z.ZodMiniType<
  ExternalAddressControlCapabilities,
  unknown
> = z.object({
  networks: z.array(ExternalAddressControlCapability$inboundSchema),
});

export function externalAddressControlCapabilitiesFromJSON(
  jsonString: string,
): SafeParseResult<ExternalAddressControlCapabilities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExternalAddressControlCapabilities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalAddressControlCapabilities' from JSON`,
  );
}
