/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bc0523670819
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
 */
export const FeePolicyModeInputEnum = {
  BuyerPays: "buyer_pays",
  TenantAbsorbsUpToCap: "tenant_absorbs_up_to_cap",
} as const;
/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
 */
export type FeePolicyModeInputEnum = OpenEnum<typeof FeePolicyModeInputEnum>;

/** @internal */
export const FeePolicyModeInputEnum$inboundSchema: z.ZodMiniType<
  FeePolicyModeInputEnum,
  unknown
> = openEnums.inboundSchema(FeePolicyModeInputEnum);
/** @internal */
export const FeePolicyModeInputEnum$outboundSchema: z.ZodMiniType<
  string,
  FeePolicyModeInputEnum
> = openEnums.outboundSchema(FeePolicyModeInputEnum);
