/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 76a555e390a1
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `USD` - USD
 */
export const FeePolicyQuoteCurrencyInputEnum = {
  Usd: "USD",
} as const;
/**
 * * `USD` - USD
 */
export type FeePolicyQuoteCurrencyInputEnum = ClosedEnum<
  typeof FeePolicyQuoteCurrencyInputEnum
>;

/** @internal */
export const FeePolicyQuoteCurrencyInputEnum$inboundSchema: z.ZodMiniEnum<
  typeof FeePolicyQuoteCurrencyInputEnum
> = z.enum(FeePolicyQuoteCurrencyInputEnum);
/** @internal */
export const FeePolicyQuoteCurrencyInputEnum$outboundSchema: z.ZodMiniEnum<
  typeof FeePolicyQuoteCurrencyInputEnum
> = FeePolicyQuoteCurrencyInputEnum$inboundSchema;
