/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 98b21406d617
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `sponsored` - sponsored
 */
export const GasModeEnum = {
  BuyerPays: "buyer_pays",
  Sponsored: "sponsored",
} as const;
/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `sponsored` - sponsored
 */
export type GasModeEnum = OpenEnum<typeof GasModeEnum>;

/** @internal */
export const GasModeEnum$inboundSchema: z.ZodMiniType<GasModeEnum, unknown> =
  openEnums.inboundSchema(GasModeEnum);
