/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3b5d692ebcb1
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `GET` - GET
 *
 * @remarks
 * * `POST` - POST
 * * `PUT` - PUT
 * * `PATCH` - PATCH
 * * `DELETE` - DELETE
 */
export const HTTPMethodEnum = {
  Get: "GET",
  Post: "POST",
  Put: "PUT",
  Patch: "PATCH",
  Delete: "DELETE",
} as const;
/**
 * * `GET` - GET
 *
 * @remarks
 * * `POST` - POST
 * * `PUT` - PUT
 * * `PATCH` - PATCH
 * * `DELETE` - DELETE
 */
export type HTTPMethodEnum = ClosedEnum<typeof HTTPMethodEnum>;

/** @internal */
export const HTTPMethodEnum$outboundSchema: z.ZodMiniEnum<
  typeof HTTPMethodEnum
> = z.enum(HTTPMethodEnum);
