/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a1b88c9124c4
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type HTTPMetadata = {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  response: Response;
  /**
   * Raw HTTP request; suitable for debugging
   */
  request: Request;
};

/** @internal */
export const HTTPMetadata$inboundSchema: z.ZodMiniType<HTTPMetadata, unknown> =
  z.pipe(
    z.object({
      Response: z.custom<Response>(x => x instanceof Response),
      Request: z.custom<Request>(x => x instanceof Request),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Response": "response",
        "Request": "request",
      });
    }),
  );

export function httpMetadataFromJSON(
  jsonString: string,
): SafeParseResult<HTTPMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HTTPMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HTTPMetadata' from JSON`,
  );
}
