/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eac804f14012
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * * `absent` - absent
 *
 * @remarks
 * * `in_progress` - in_progress
 * * `completed` - completed
 */
export const State = {
  Absent: "absent",
  InProgress: "in_progress",
  Completed: "completed",
} as const;
/**
 * * `absent` - absent
 *
 * @remarks
 * * `in_progress` - in_progress
 * * `completed` - completed
 */
export type State = OpenEnum<typeof State>;

export type IdempotencyOutcome = {
  state: State;
};

/** @internal */
export const State$inboundSchema: z.ZodMiniType<State, unknown> = openEnums
  .inboundSchema(State);

/** @internal */
export const IdempotencyOutcome$inboundSchema: z.ZodMiniType<
  IdempotencyOutcome,
  unknown
> = z.object({
  state: State$inboundSchema,
});

export function idempotencyOutcomeFromJSON(
  jsonString: string,
): SafeParseResult<IdempotencyOutcome, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdempotencyOutcome$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdempotencyOutcome' from JSON`,
  );
}
