/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cb5bad907d7d
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type NativeFeeObservationEvidence = {
  source: string;
  nativeFeeAtomic: string;
  observedAt: Date;
};

/** @internal */
export const NativeFeeObservationEvidence$inboundSchema: z.ZodMiniType<
  NativeFeeObservationEvidence,
  unknown
> = z.object({
  source: types.string(),
  nativeFeeAtomic: types.string(),
  observedAt: types.date(),
});

export function nativeFeeObservationEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<NativeFeeObservationEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NativeFeeObservationEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NativeFeeObservationEvidence' from JSON`,
  );
}
