/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4383bc453c26
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type NativeUsdObservationEvidence = {
  source: string;
  nativeUsdQuoteMicros: string;
  observedAt: Date;
};

/** @internal */
export const NativeUsdObservationEvidence$inboundSchema: z.ZodMiniType<
  NativeUsdObservationEvidence,
  unknown
> = z.object({
  source: types.string(),
  nativeUsdQuoteMicros: types.string(),
  observedAt: types.date(),
});

export function nativeUsdObservationEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<NativeUsdObservationEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NativeUsdObservationEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NativeUsdObservationEvidence' from JSON`,
  );
}
