/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 821d99edad37
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  NetworkFeePreviewPrice,
  NetworkFeePreviewPrice$Outbound,
  NetworkFeePreviewPrice$outboundSchema,
} from "./network-fee-preview-price.js";

/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
 */
export const FeeMode = {
  BuyerPays: "buyer_pays",
  TenantAbsorbsUpToCap: "tenant_absorbs_up_to_cap",
} as const;
/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
 */
export type FeeMode = ClosedEnum<typeof FeeMode>;

/**
 * * `USD` - USD
 */
export const QuoteCurrency = {
  Usd: "USD",
} as const;
/**
 * * `USD` - USD
 */
export type QuoteCurrency = ClosedEnum<typeof QuoteCurrency>;

export type NetworkFeePreview = {
  feeMode?: FeeMode | undefined;
  quoteCurrency?: QuoteCurrency | undefined;
  feeAllowanceCapQuoteMicros?: string | undefined;
  prices: Array<NetworkFeePreviewPrice>;
};

/** @internal */
export const FeeMode$outboundSchema: z.ZodMiniEnum<typeof FeeMode> = z.enum(
  FeeMode,
);

/** @internal */
export const QuoteCurrency$outboundSchema: z.ZodMiniEnum<typeof QuoteCurrency> =
  z.enum(QuoteCurrency);

/** @internal */
export type NetworkFeePreview$Outbound = {
  fee_mode: string;
  quote_currency: string;
  fee_allowance_cap_quote_micros: string;
  prices: Array<NetworkFeePreviewPrice$Outbound>;
};

/** @internal */
export const NetworkFeePreview$outboundSchema: z.ZodMiniType<
  NetworkFeePreview$Outbound,
  NetworkFeePreview
> = z.pipe(
  z.object({
    feeMode: z._default(FeeMode$outboundSchema, "buyer_pays"),
    quoteCurrency: z._default(QuoteCurrency$outboundSchema, "USD"),
    feeAllowanceCapQuoteMicros: z._default(z.string(), "0"),
    prices: z.array(NetworkFeePreviewPrice$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      feeMode: "fee_mode",
      quoteCurrency: "quote_currency",
      feeAllowanceCapQuoteMicros: "fee_allowance_cap_quote_micros",
    });
  }),
);

export function networkFeePreviewToJSON(
  networkFeePreview: NetworkFeePreview,
): string {
  return JSON.stringify(
    NetworkFeePreview$outboundSchema.parse(networkFeePreview),
  );
}
