/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 082d0884cb05
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FeePolicyModeInputEnum,
  FeePolicyModeInputEnum$inboundSchema,
} from "./fee-policy-mode-input-enum.js";
import {
  FeePolicyQuoteCurrencyInputEnum,
  FeePolicyQuoteCurrencyInputEnum$inboundSchema,
} from "./fee-policy-quote-currency-input-enum.js";
import {
  NetworkFeeEvidence,
  NetworkFeeEvidence$inboundSchema,
} from "./network-fee-evidence.js";

export type NetworkFeeAlternative = {
  type: string;
  version: number;
  network: string;
  assetId: string;
  contractAddress: string;
  /**
   * * `buyer_pays` - buyer_pays
   *
   * @remarks
   * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
   */
  feeMode: FeePolicyModeInputEnum;
  /**
   * * `USD` - USD
   */
  quoteCurrency: FeePolicyQuoteCurrencyInputEnum;
  listedAmountAtomic: string;
  feeAllowanceCapQuoteMicros: string;
  estimatedNativeFeeAtomic: string | null;
  nativeSymbol: string | null;
  nativeDecimals: number | null;
  nativeUsdQuoteMicros: string | null;
  estimatedFeeQuoteMicros: string | null;
  providerDisagreementBps: number | null;
  feeAllowanceQuoteMicros: string;
  feeAllowanceAtomic: string;
  buyerPaymentAtomic: string;
  tenantProceedsAtomic: string;
  quoteExpiresAt: Date | null;
  /**
   * Published shape for available and explicitly unavailable fee evidence.
   */
  feeEvidence: NetworkFeeEvidence;
  feeEvidenceDigest: string;
  eligible: boolean;
  exclusionReason: string | null;
};

/** @internal */
export const NetworkFeeAlternative$inboundSchema: z.ZodMiniType<
  NetworkFeeAlternative,
  unknown
> = z.object({
  type: types.string(),
  version: types.number(),
  network: types.string(),
  assetId: types.string(),
  contractAddress: types.string(),
  feeMode: FeePolicyModeInputEnum$inboundSchema,
  quoteCurrency: FeePolicyQuoteCurrencyInputEnum$inboundSchema,
  listedAmountAtomic: types.string(),
  feeAllowanceCapQuoteMicros: types.string(),
  estimatedNativeFeeAtomic: types.nullable(types.string()),
  nativeSymbol: types.nullable(types.string()),
  nativeDecimals: types.nullable(types.number()),
  nativeUsdQuoteMicros: types.nullable(types.string()),
  estimatedFeeQuoteMicros: types.nullable(types.string()),
  providerDisagreementBps: types.nullable(types.number()),
  feeAllowanceQuoteMicros: types.string(),
  feeAllowanceAtomic: types.string(),
  buyerPaymentAtomic: types.string(),
  tenantProceedsAtomic: types.string(),
  quoteExpiresAt: types.nullable(types.date()),
  feeEvidence: NetworkFeeEvidence$inboundSchema,
  feeEvidenceDigest: types.string(),
  eligible: types.boolean(),
  exclusionReason: types.nullable(types.string()),
});

export function networkFeeAlternativeFromJSON(
  jsonString: string,
): SafeParseResult<NetworkFeeAlternative, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkFeeAlternative$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkFeeAlternative' from JSON`,
  );
}
