/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PublicFeePolicyDocument,
  PublicFeePolicyDocument$inboundSchema,
} from "./public-fee-policy-document.js";
import {
  PublicNetworkFeeAlternative,
  PublicNetworkFeeAlternative$inboundSchema,
} from "./public-network-fee-alternative.js";

export type NetworkFeePreviewResponse = {
  feePolicy: PublicFeePolicyDocument;
  alternatives: Array<PublicNetworkFeeAlternative>;
  feeQuoteDigest: string;
};

/** @internal */
export const NetworkFeePreviewResponse$inboundSchema: z.ZodMiniType<
  NetworkFeePreviewResponse,
  unknown
> = z.pipe(
  z.object({
    fee_policy: PublicFeePolicyDocument$inboundSchema,
    alternatives: z.array(PublicNetworkFeeAlternative$inboundSchema),
    fee_quote_digest: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "fee_policy": "feePolicy",
      "fee_quote_digest": "feeQuoteDigest",
    });
  }),
);

export function networkFeePreviewResponseFromJSON(
  jsonString: string,
): SafeParseResult<NetworkFeePreviewResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkFeePreviewResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkFeePreviewResponse' from JSON`,
  );
}
