/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5738130b31c3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type NetworkFeePreviewPrice = {
  assetId: string;
  listedAmountAtomic: string;
};

/** @internal */
export type NetworkFeePreviewPrice$Outbound = {
  asset_id: string;
  listed_amount_atomic: string;
};

/** @internal */
export const NetworkFeePreviewPrice$outboundSchema: z.ZodMiniType<
  NetworkFeePreviewPrice$Outbound,
  NetworkFeePreviewPrice
> = z.pipe(
  z.object({
    assetId: z.string(),
    listedAmountAtomic: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      assetId: "asset_id",
      listedAmountAtomic: "listed_amount_atomic",
    });
  }),
);

export function networkFeePreviewPriceToJSON(
  networkFeePreviewPrice: NetworkFeePreviewPrice,
): string {
  return JSON.stringify(
    NetworkFeePreviewPrice$outboundSchema.parse(networkFeePreviewPrice),
  );
}
