/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1702fc816dbb
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  NativeFeeObservationEvidence,
  NativeFeeObservationEvidence$inboundSchema,
} from "./native-fee-observation-evidence.js";
import {
  NativeUsdObservationEvidence,
  NativeUsdObservationEvidence$inboundSchema,
} from "./native-usd-observation-evidence.js";

/**
 * Published shape for available and explicitly unavailable fee evidence.
 */
export type NetworkFeeEvidence = {
  type: string;
  version: number;
  network: string;
  assetId: string;
  payloadProfile: string;
  nativeSymbol?: string | undefined;
  nativeDecimals?: number | undefined;
  nativeFeeObservations?: Array<NativeFeeObservationEvidence> | undefined;
  nativeUsdObservations?: Array<NativeUsdObservationEvidence> | undefined;
  expiresAt?: Date | undefined;
};

/** @internal */
export const NetworkFeeEvidence$inboundSchema: z.ZodMiniType<
  NetworkFeeEvidence,
  unknown
> = z.object({
  type: types.string(),
  version: types.number(),
  network: types.string(),
  assetId: types.string(),
  payloadProfile: types.string(),
  nativeSymbol: types.optional(types.string()),
  nativeDecimals: types.optional(types.number()),
  nativeFeeObservations: types.optional(
    z.array(NativeFeeObservationEvidence$inboundSchema),
  ),
  nativeUsdObservations: types.optional(
    z.array(NativeUsdObservationEvidence$inboundSchema),
  ),
  expiresAt: types.optional(types.date()),
});

export function networkFeeEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<NetworkFeeEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkFeeEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkFeeEvidence' from JSON`,
  );
}
