/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4e58fb669f39
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ObservationBlock = {
  number: string;
  hash: string;
  finality: string;
};

/** @internal */
export const ObservationBlock$inboundSchema: z.ZodMiniType<
  ObservationBlock,
  unknown
> = z.object({
  number: types.string(),
  hash: types.string(),
  finality: types.string(),
});

export function observationBlockFromJSON(
  jsonString: string,
): SafeParseResult<ObservationBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ObservationBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ObservationBlock' from JSON`,
  );
}
