/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 185422e9e2b7
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `healthy` - healthy
 *
 * @remarks
 * * `degraded` - degraded
 * * `unavailable` - unavailable
 */
export const ObservationStateEnum = {
  Healthy: "healthy",
  Degraded: "degraded",
  Unavailable: "unavailable",
} as const;
/**
 * * `healthy` - healthy
 *
 * @remarks
 * * `degraded` - degraded
 * * `unavailable` - unavailable
 */
export type ObservationStateEnum = OpenEnum<typeof ObservationStateEnum>;

/** @internal */
export const ObservationStateEnum$inboundSchema: z.ZodMiniType<
  ObservationStateEnum,
  unknown
> = openEnums.inboundSchema(ObservationStateEnum);
