/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8ebfc9e4c369
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * * `created` - Created
 *
 * @remarks
 * * `payment_pending` - Payment pending
 * * `paid` - Paid
 * * `fulfillment_pending` - Fulfillment pending
 * * `fulfilled` - Fulfilled
 * * `expired` - Expired
 * * `failed` - Failed
 */
export const Status = {
  Created: "created",
  PaymentPending: "payment_pending",
  Paid: "paid",
  FulfillmentPending: "fulfillment_pending",
  Fulfilled: "fulfilled",
  Expired: "expired",
  Failed: "failed",
} as const;
/**
 * * `created` - Created
 *
 * @remarks
 * * `payment_pending` - Payment pending
 * * `paid` - Paid
 * * `fulfillment_pending` - Fulfillment pending
 * * `fulfilled` - Fulfilled
 * * `expired` - Expired
 * * `failed` - Failed
 */
export type Status = OpenEnum<typeof Status>;

export type Order = {
  id: string;
  resourceVersionId: string;
  requestFingerprint: string;
  paymentIdentifier: string;
  buyerPaymentIdentifier: string | null;
  status: Status;
  paidAt: Date | null;
  fulfilledAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> = openEnums
  .inboundSchema(Status);

/** @internal */
export const Order$inboundSchema: z.ZodMiniType<Order, unknown> = z.pipe(
  z.object({
    id: types.string(),
    resource_version_id: types.string(),
    request_fingerprint: types.string(),
    payment_identifier: types.string(),
    buyer_payment_identifier: types.nullable(types.string()),
    status: Status$inboundSchema,
    paid_at: types.nullable(types.date()),
    fulfilled_at: types.nullable(types.date()),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "resource_version_id": "resourceVersionId",
      "request_fingerprint": "requestFingerprint",
      "payment_identifier": "paymentIdentifier",
      "buyer_payment_identifier": "buyerPaymentIdentifier",
      "paid_at": "paidAt",
      "fulfilled_at": "fulfilledAt",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function orderFromJSON(
  jsonString: string,
): SafeParseResult<Order, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Order$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Order' from JSON`,
  );
}
