/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FeePolicyModeInputEnum,
  FeePolicyModeInputEnum$inboundSchema,
} from "./fee-policy-mode-input-enum.js";
import {
  FeePolicyQuoteCurrencyInputEnum,
  FeePolicyQuoteCurrencyInputEnum$inboundSchema,
} from "./fee-policy-quote-currency-input-enum.js";
import {
  PublicNetworkFeeAlternative,
  PublicNetworkFeeAlternative$inboundSchema,
} from "./public-network-fee-alternative.js";

export type FeePolicy = {
  type: string;
  version: number;
  /**
   * * `buyer_pays` - buyer_pays
   *
   * @remarks
   * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
   */
  feeMode: FeePolicyModeInputEnum;
  /**
   * * `USD` - USD
   */
  quoteCurrency: FeePolicyQuoteCurrencyInputEnum;
};

export type PaymentReceipt = {
  id: string;
  orderId: string;
  settlementJobId: string;
  receipt: any;
  receiptDigest: string;
  signature: string;
  signingKeyVersion: string;
  eligibleAlternatives: Array<PublicNetworkFeeAlternative>;
  feePolicy: FeePolicy | null;
  feeEvidence: { [k: string]: any } | null;
  feeQuoteDigest: string | null;
  feeQuoteExpiresAt: Date | null;
  settlementAmountAtomic: string;
  gasMode: string;
  buyerNativeFeeAtomic: string | null;
  sponsoredNativeFeeAtomic: string | null;
  sponsoredNativeSymbol: string | null;
  tenantGasChargeMicros: string | null;
  gasSponsorshipEvidenceDigest: string | null;
  createdAt: Date;
};

/** @internal */
export const FeePolicy$inboundSchema: z.ZodMiniType<FeePolicy, unknown> = z
  .object({
    type: types.string(),
    version: types.number(),
    feeMode: FeePolicyModeInputEnum$inboundSchema,
    quoteCurrency: FeePolicyQuoteCurrencyInputEnum$inboundSchema,
  });

export function feePolicyFromJSON(
  jsonString: string,
): SafeParseResult<FeePolicy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeePolicy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeePolicy' from JSON`,
  );
}

/** @internal */
export const PaymentReceipt$inboundSchema: z.ZodMiniType<
  PaymentReceipt,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    order_id: types.string(),
    settlement_job_id: types.string(),
    receipt: z.any(),
    receipt_digest: types.string(),
    signature: types.string(),
    signing_key_version: types.string(),
    eligible_alternatives: z.array(PublicNetworkFeeAlternative$inboundSchema),
    fee_policy: types.nullable(z.lazy(() => FeePolicy$inboundSchema)),
    fee_evidence: types.nullable(z.record(z.string(), z.any())),
    fee_quote_digest: types.nullable(types.string()),
    fee_quote_expires_at: types.nullable(types.date()),
    settlement_amount_atomic: types.string(),
    gas_mode: types.string(),
    buyer_native_fee_atomic: types.nullable(types.string()),
    sponsored_native_fee_atomic: types.nullable(types.string()),
    sponsored_native_symbol: types.nullable(types.string()),
    tenant_gas_charge_micros: types.nullable(types.string()),
    gas_sponsorship_evidence_digest: types.nullable(types.string()),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "order_id": "orderId",
      "settlement_job_id": "settlementJobId",
      "receipt_digest": "receiptDigest",
      "signing_key_version": "signingKeyVersion",
      "eligible_alternatives": "eligibleAlternatives",
      "fee_policy": "feePolicy",
      "fee_evidence": "feeEvidence",
      "fee_quote_digest": "feeQuoteDigest",
      "fee_quote_expires_at": "feeQuoteExpiresAt",
      "settlement_amount_atomic": "settlementAmountAtomic",
      "gas_mode": "gasMode",
      "buyer_native_fee_atomic": "buyerNativeFeeAtomic",
      "sponsored_native_fee_atomic": "sponsoredNativeFeeAtomic",
      "sponsored_native_symbol": "sponsoredNativeSymbol",
      "tenant_gas_charge_micros": "tenantGasChargeMicros",
      "gas_sponsorship_evidence_digest": "gasSponsorshipEvidenceDigest",
      "created_at": "createdAt",
    });
  }),
);

export function paymentReceiptFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReceipt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReceipt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReceipt' from JSON`,
  );
}
