/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1b2024589240
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaymentReadinessRail,
  PaymentReadinessRail$inboundSchema,
} from "./payment-readiness-rail.js";

export type PaymentReadiness = {
  observedAt: Date;
  tenantStatus: string;
  tenantAcceptingNewChallenges: boolean;
  globalChallengesEnabled: boolean;
  globalSettlementEnabled: boolean;
  controlPlaneReadyForNewChallenges: boolean;
  controlPlaneReadyForSettlement: boolean;
  externalOnboarding: any;
  rails: Array<PaymentReadinessRail>;
};

/** @internal */
export const PaymentReadiness$inboundSchema: z.ZodMiniType<
  PaymentReadiness,
  unknown
> = z.pipe(
  z.object({
    observed_at: types.date(),
    tenant_status: types.string(),
    tenant_accepting_new_challenges: types.boolean(),
    global_challenges_enabled: types.boolean(),
    global_settlement_enabled: types.boolean(),
    control_plane_ready_for_new_challenges: types.boolean(),
    control_plane_ready_for_settlement: types.boolean(),
    external_onboarding: z.any(),
    rails: z.array(PaymentReadinessRail$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "observed_at": "observedAt",
      "tenant_status": "tenantStatus",
      "tenant_accepting_new_challenges": "tenantAcceptingNewChallenges",
      "global_challenges_enabled": "globalChallengesEnabled",
      "global_settlement_enabled": "globalSettlementEnabled",
      "control_plane_ready_for_new_challenges":
        "controlPlaneReadyForNewChallenges",
      "control_plane_ready_for_settlement": "controlPlaneReadyForSettlement",
      "external_onboarding": "externalOnboarding",
    });
  }),
);

export function paymentReadinessFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReadiness, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReadiness$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReadiness' from JSON`,
  );
}
