/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 129e7c31fcfa
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * * `tenant_action` - tenant_action
 *
 * @remarks
 * * `automatic_platform_recovery` - automatic_platform_recovery
 * * `manual_platform_pause` - manual_platform_pause
 */
export const Owner = {
  TenantAction: "tenant_action",
  AutomaticPlatformRecovery: "automatic_platform_recovery",
  ManualPlatformPause: "manual_platform_pause",
} as const;
/**
 * * `tenant_action` - tenant_action
 *
 * @remarks
 * * `automatic_platform_recovery` - automatic_platform_recovery
 * * `manual_platform_pause` - manual_platform_pause
 */
export type Owner = OpenEnum<typeof Owner>;

export type PaymentReadinessBlocker = {
  code: string;
  owner: Owner;
  message: string;
  actionUrl?: string | undefined;
};

/** @internal */
export const Owner$inboundSchema: z.ZodMiniType<Owner, unknown> = openEnums
  .inboundSchema(Owner);

/** @internal */
export const PaymentReadinessBlocker$inboundSchema: z.ZodMiniType<
  PaymentReadinessBlocker,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    owner: Owner$inboundSchema,
    message: types.string(),
    action_url: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "action_url": "actionUrl",
    });
  }),
);

export function paymentReadinessBlockerFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReadinessBlocker, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReadinessBlocker$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReadinessBlocker' from JSON`,
  );
}
