/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 141f5d6992a8
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FeePolicyModeInputEnum,
  FeePolicyModeInputEnum$inboundSchema,
} from "./fee-policy-mode-input-enum.js";
import {
  FeePolicyQuoteCurrencyInputEnum,
  FeePolicyQuoteCurrencyInputEnum$inboundSchema,
} from "./fee-policy-quote-currency-input-enum.js";
import {
  NativeFeeObservationEvidence,
  NativeFeeObservationEvidence$inboundSchema,
} from "./native-fee-observation-evidence.js";
import {
  NativeUsdObservationEvidence,
  NativeUsdObservationEvidence$inboundSchema,
} from "./native-usd-observation-evidence.js";
import {
  NetworkFeeAlternative,
  NetworkFeeAlternative$inboundSchema,
} from "./network-fee-alternative.js";

export type FeePolicy = {
  type: string;
  version: number;
  /**
   * * `buyer_pays` - buyer_pays
   *
   * @remarks
   * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
   */
  feeMode: FeePolicyModeInputEnum;
  /**
   * * `USD` - USD
   */
  quoteCurrency: FeePolicyQuoteCurrencyInputEnum;
  feeAllowanceCapQuoteMicros: string;
};

/**
 * Published shape for available and explicitly unavailable fee evidence.
 */
export type FeeEvidence = {
  type: string;
  version: number;
  network: string;
  assetId: string;
  payloadProfile: string;
  nativeSymbol?: string | undefined;
  nativeDecimals?: number | undefined;
  nativeFeeObservations?: Array<NativeFeeObservationEvidence> | undefined;
  nativeUsdObservations?: Array<NativeUsdObservationEvidence> | undefined;
  expiresAt?: Date | undefined;
};

export type PaymentReceipt = {
  id: string;
  orderId: string;
  settlementJobId: string;
  receipt: any;
  receiptDigest: string;
  signature: string;
  signingKeyVersion: string;
  eligibleAlternatives: Array<NetworkFeeAlternative>;
  feePolicy: FeePolicy | null;
  feeEvidence: FeeEvidence | null;
  feeQuoteDigest: string | null;
  feeQuoteExpiresAt: Date | null;
  settlementAmountAtomic: string;
  createdAt: Date;
};

/** @internal */
export const FeePolicy$inboundSchema: z.ZodMiniType<FeePolicy, unknown> = z
  .object({
    type: types.string(),
    version: types.number(),
    feeMode: FeePolicyModeInputEnum$inboundSchema,
    quoteCurrency: FeePolicyQuoteCurrencyInputEnum$inboundSchema,
    feeAllowanceCapQuoteMicros: types.string(),
  });

export function feePolicyFromJSON(
  jsonString: string,
): SafeParseResult<FeePolicy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeePolicy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeePolicy' from JSON`,
  );
}

/** @internal */
export const FeeEvidence$inboundSchema: z.ZodMiniType<FeeEvidence, unknown> = z
  .object({
    type: types.string(),
    version: types.number(),
    network: types.string(),
    assetId: types.string(),
    payloadProfile: types.string(),
    nativeSymbol: types.optional(types.string()),
    nativeDecimals: types.optional(types.number()),
    nativeFeeObservations: types.optional(
      z.array(NativeFeeObservationEvidence$inboundSchema),
    ),
    nativeUsdObservations: types.optional(
      z.array(NativeUsdObservationEvidence$inboundSchema),
    ),
    expiresAt: types.optional(types.date()),
  });

export function feeEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<FeeEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeeEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeeEvidence' from JSON`,
  );
}

/** @internal */
export const PaymentReceipt$inboundSchema: z.ZodMiniType<
  PaymentReceipt,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    order_id: types.string(),
    settlement_job_id: types.string(),
    receipt: z.any(),
    receipt_digest: types.string(),
    signature: types.string(),
    signing_key_version: types.string(),
    eligible_alternatives: z.array(NetworkFeeAlternative$inboundSchema),
    fee_policy: types.nullable(z.lazy(() => FeePolicy$inboundSchema)),
    fee_evidence: types.nullable(z.lazy(() => FeeEvidence$inboundSchema)),
    fee_quote_digest: types.nullable(types.string()),
    fee_quote_expires_at: types.nullable(types.date()),
    settlement_amount_atomic: types.string(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "order_id": "orderId",
      "settlement_job_id": "settlementJobId",
      "receipt_digest": "receiptDigest",
      "signing_key_version": "signingKeyVersion",
      "eligible_alternatives": "eligibleAlternatives",
      "fee_policy": "feePolicy",
      "fee_evidence": "feeEvidence",
      "fee_quote_digest": "feeQuoteDigest",
      "fee_quote_expires_at": "feeQuoteExpiresAt",
      "settlement_amount_atomic": "settlementAmountAtomic",
      "created_at": "createdAt",
    });
  }),
);

export function paymentReceiptFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReceipt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReceipt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReceipt' from JSON`,
  );
}
