/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaymentReadinessAsset,
  PaymentReadinessAsset$inboundSchema,
} from "./payment-readiness-asset.js";
import {
  PaymentReadinessBlocker,
  PaymentReadinessBlocker$inboundSchema,
} from "./payment-readiness-blocker.js";

export type PaymentReadinessRail = {
  assetId: string;
  network: string;
  symbol: string;
  selected: boolean;
  walletReady: boolean;
  platformAvailable: boolean;
  acceptingNewPayments: boolean;
  readyForNewPayment: boolean;
  readinessValidUntil: Date | null;
  feeQuoteReady: boolean;
  feeQuoteValidUntil: Date | null;
  status: string;
  blockers: Array<PaymentReadinessBlocker>;
  tenantChallengesEnabled: boolean;
  tenantSettlementEnabled: boolean;
  networkAssistanceEnabled: boolean;
  challengeControlReady: boolean;
  settlementControlReady: boolean;
  assets: Array<PaymentReadinessAsset>;
};

/** @internal */
export const PaymentReadinessRail$inboundSchema: z.ZodMiniType<
  PaymentReadinessRail,
  unknown
> = z.pipe(
  z.object({
    asset_id: types.string(),
    network: types.string(),
    symbol: types.string(),
    selected: types.boolean(),
    wallet_ready: types.boolean(),
    platform_available: types.boolean(),
    accepting_new_payments: types.boolean(),
    ready_for_new_payment: types.boolean(),
    readiness_valid_until: types.nullable(types.date()),
    fee_quote_ready: types.boolean(),
    fee_quote_valid_until: types.nullable(types.date()),
    status: types.string(),
    blockers: z.array(PaymentReadinessBlocker$inboundSchema),
    tenant_challenges_enabled: types.boolean(),
    tenant_settlement_enabled: types.boolean(),
    network_assistance_enabled: types.boolean(),
    challenge_control_ready: types.boolean(),
    settlement_control_ready: types.boolean(),
    assets: z.array(PaymentReadinessAsset$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "wallet_ready": "walletReady",
      "platform_available": "platformAvailable",
      "accepting_new_payments": "acceptingNewPayments",
      "ready_for_new_payment": "readyForNewPayment",
      "readiness_valid_until": "readinessValidUntil",
      "fee_quote_ready": "feeQuoteReady",
      "fee_quote_valid_until": "feeQuoteValidUntil",
      "tenant_challenges_enabled": "tenantChallengesEnabled",
      "tenant_settlement_enabled": "tenantSettlementEnabled",
      "network_assistance_enabled": "networkAssistanceEnabled",
      "challenge_control_ready": "challengeControlReady",
      "settlement_control_ready": "settlementControlReady",
    });
  }),
);

export function paymentReadinessRailFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReadinessRail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReadinessRail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReadinessRail' from JSON`,
  );
}
