/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ReceiptStatusEnum,
  ReceiptStatusEnum$inboundSchema,
} from "./receipt-status-enum.js";

export type PaymentReceiptStatus = {
  paymentId: string;
  state: string;
  confirmed: boolean;
  finalized: boolean;
  confirmedAt: Date | null;
  finalizedAt: Date | null;
  transaction: string;
  network: string;
  /**
   * * `pending_confirmation` - pending_confirmation
   *
   * @remarks
   * * `pending_finality` - pending_finality
   */
  receiptStatus: ReceiptStatusEnum;
};

/** @internal */
export const PaymentReceiptStatus$inboundSchema: z.ZodMiniType<
  PaymentReceiptStatus,
  unknown
> = z.pipe(
  z.object({
    payment_id: types.string(),
    state: types.string(),
    confirmed: types.boolean(),
    finalized: types.boolean(),
    confirmed_at: types.nullable(types.date()),
    finalized_at: types.nullable(types.date()),
    transaction: types.string(),
    network: types.string(),
    receipt_status: ReceiptStatusEnum$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "payment_id": "paymentId",
      "confirmed_at": "confirmedAt",
      "finalized_at": "finalizedAt",
      "receipt_status": "receiptStatus",
    });
  }),
);

export function paymentReceiptStatusFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReceiptStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReceiptStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReceiptStatus' from JSON`,
  );
}
