/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a3e44ee85286
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PaymentReadinessAsset = {
  assetId: string;
  displayName: string;
  contractAddress: string;
  issuerNative: boolean;
  registryEnabled: boolean;
  tenantEnabled: boolean;
  operatorAssistanceEnabled: boolean;
  baseReadinessBlockers: Array<string>;
  challengeControlReady: boolean;
  settlementControlReady: boolean;
};

/** @internal */
export const PaymentReadinessAsset$inboundSchema: z.ZodMiniType<
  PaymentReadinessAsset,
  unknown
> = z.pipe(
  z.object({
    asset_id: types.string(),
    display_name: types.string(),
    contract_address: types.string(),
    issuer_native: types.boolean(),
    registry_enabled: types.boolean(),
    tenant_enabled: types.boolean(),
    operator_assistance_enabled: types.boolean(),
    base_readiness_blockers: z.array(types.string()),
    challenge_control_ready: types.boolean(),
    settlement_control_ready: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "display_name": "displayName",
      "contract_address": "contractAddress",
      "issuer_native": "issuerNative",
      "registry_enabled": "registryEnabled",
      "tenant_enabled": "tenantEnabled",
      "operator_assistance_enabled": "operatorAssistanceEnabled",
      "base_readiness_blockers": "baseReadinessBlockers",
      "challenge_control_ready": "challengeControlReady",
      "settlement_control_ready": "settlementControlReady",
    });
  }),
);

export function paymentReadinessAssetFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReadinessAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReadinessAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReadinessAsset' from JSON`,
  );
}
