/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d713d14c71d4
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaymentReadinessAsset,
  PaymentReadinessAsset$inboundSchema,
} from "./payment-readiness-asset.js";

export type PaymentReadinessRail = {
  network: string;
  tenantChallengesEnabled: boolean;
  tenantSettlementEnabled: boolean;
  networkAssistanceEnabled: boolean;
  challengeControlReady: boolean;
  settlementControlReady: boolean;
  assets: Array<PaymentReadinessAsset>;
};

/** @internal */
export const PaymentReadinessRail$inboundSchema: z.ZodMiniType<
  PaymentReadinessRail,
  unknown
> = z.pipe(
  z.object({
    network: types.string(),
    tenant_challenges_enabled: types.boolean(),
    tenant_settlement_enabled: types.boolean(),
    network_assistance_enabled: types.boolean(),
    challenge_control_ready: types.boolean(),
    settlement_control_ready: types.boolean(),
    assets: z.array(PaymentReadinessAsset$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tenant_challenges_enabled": "tenantChallengesEnabled",
      "tenant_settlement_enabled": "tenantSettlementEnabled",
      "network_assistance_enabled": "networkAssistanceEnabled",
      "challenge_control_ready": "challengeControlReady",
      "settlement_control_ready": "settlementControlReady",
    });
  }),
);

export function paymentReadinessRailFromJSON(
  jsonString: string,
): SafeParseResult<PaymentReadinessRail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentReadinessRail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentReadinessRail' from JSON`,
  );
}
