/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5f1458aa0cbe
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PriceInput = {
  assetId: string;
  walletVersionId: string;
  amountAtomic: string;
  maxTimeoutSeconds: number;
};

/** @internal */
export type PriceInput$Outbound = {
  asset_id: string;
  wallet_version_id: string;
  amount_atomic: string;
  max_timeout_seconds: number;
};

/** @internal */
export const PriceInput$outboundSchema: z.ZodMiniType<
  PriceInput$Outbound,
  PriceInput
> = z.pipe(
  z.object({
    assetId: z.string(),
    walletVersionId: z.string(),
    amountAtomic: z.string(),
    maxTimeoutSeconds: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      assetId: "asset_id",
      walletVersionId: "wallet_version_id",
      amountAtomic: "amount_atomic",
      maxTimeoutSeconds: "max_timeout_seconds",
    });
  }),
);

export function priceInputToJSON(priceInput: PriceInput): string {
  return JSON.stringify(PriceInput$outboundSchema.parse(priceInput));
}
