/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FeePolicyModeInputEnum,
  FeePolicyModeInputEnum$inboundSchema,
} from "./fee-policy-mode-input-enum.js";
import {
  FeePolicyQuoteCurrencyInputEnum,
  FeePolicyQuoteCurrencyInputEnum$inboundSchema,
} from "./fee-policy-quote-currency-input-enum.js";

export type PublicFeePolicyDocument = {
  type: string;
  version: number;
  /**
   * * `buyer_pays` - buyer_pays
   *
   * @remarks
   * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
   */
  feeMode: FeePolicyModeInputEnum;
  /**
   * * `USD` - USD
   */
  quoteCurrency: FeePolicyQuoteCurrencyInputEnum;
};

/** @internal */
export const PublicFeePolicyDocument$inboundSchema: z.ZodMiniType<
  PublicFeePolicyDocument,
  unknown
> = z.object({
  type: types.string(),
  version: types.number(),
  feeMode: FeePolicyModeInputEnum$inboundSchema,
  quoteCurrency: FeePolicyQuoteCurrencyInputEnum$inboundSchema,
});

export function publicFeePolicyDocumentFromJSON(
  jsonString: string,
): SafeParseResult<PublicFeePolicyDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicFeePolicyDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicFeePolicyDocument' from JSON`,
  );
}
