/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { GasModeEnum, GasModeEnum$inboundSchema } from "./gas-mode-enum.js";

export type PublicNetworkFeeAlternative = {
  type: string;
  version: number;
  network: string;
  assetId: string;
  contractAddress: string;
  listedAmountAtomic: string;
  /**
   * * `buyer_pays` - buyer_pays
   *
   * @remarks
   * * `sponsored` - sponsored
   */
  gasMode: GasModeEnum;
  buyerNativeFeeAtomic: string | null;
  buyerPaymentAtomic: string;
  tenantProceedsAtomic: string;
  quoteExpiresAt: Date | null;
  eligible: boolean;
  exclusionReason: string | null;
};

/** @internal */
export const PublicNetworkFeeAlternative$inboundSchema: z.ZodMiniType<
  PublicNetworkFeeAlternative,
  unknown
> = z.object({
  type: types.string(),
  version: types.number(),
  network: types.string(),
  assetId: types.string(),
  contractAddress: types.string(),
  listedAmountAtomic: types.string(),
  gasMode: GasModeEnum$inboundSchema,
  buyerNativeFeeAtomic: types.nullable(types.string()),
  buyerPaymentAtomic: types.string(),
  tenantProceedsAtomic: types.string(),
  quoteExpiresAt: types.nullable(types.date()),
  eligible: types.boolean(),
  exclusionReason: types.nullable(types.string()),
});

export function publicNetworkFeeAlternativeFromJSON(
  jsonString: string,
): SafeParseResult<PublicNetworkFeeAlternative, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicNetworkFeeAlternative$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicNetworkFeeAlternative' from JSON`,
  );
}
