/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `pending_confirmation` - pending_confirmation
 *
 * @remarks
 * * `pending_finality` - pending_finality
 */
export const ReceiptStatusEnum = {
  PendingConfirmation: "pending_confirmation",
  PendingFinality: "pending_finality",
} as const;
/**
 * * `pending_confirmation` - pending_confirmation
 *
 * @remarks
 * * `pending_finality` - pending_finality
 */
export type ReceiptStatusEnum = OpenEnum<typeof ReceiptStatusEnum>;

/** @internal */
export const ReceiptStatusEnum$inboundSchema: z.ZodMiniType<
  ReceiptStatusEnum,
  unknown
> = openEnums.inboundSchema(ReceiptStatusEnum);
