/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 85b9258b7aec
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ReceiptVerificationKey = {
  algorithm: string;
  publicKeyBase64: string;
  keyFingerprint: string;
};

/** @internal */
export const ReceiptVerificationKey$inboundSchema: z.ZodMiniType<
  ReceiptVerificationKey,
  unknown
> = z.pipe(
  z.object({
    algorithm: types.string(),
    public_key_base64: types.string(),
    key_fingerprint: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "public_key_base64": "publicKeyBase64",
      "key_fingerprint": "keyFingerprint",
    });
  }),
);

export function receiptVerificationKeyFromJSON(
  jsonString: string,
): SafeParseResult<ReceiptVerificationKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReceiptVerificationKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceiptVerificationKey' from JSON`,
  );
}
