/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: efc2609fc158
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ReceiptVerificationKey,
  ReceiptVerificationKey$inboundSchema,
} from "./receipt-verification-key.js";

export type ReceiptVerificationKeyHistory = {
  type: string;
  keys: { [k: string]: ReceiptVerificationKey };
};

/** @internal */
export const ReceiptVerificationKeyHistory$inboundSchema: z.ZodMiniType<
  ReceiptVerificationKeyHistory,
  unknown
> = z.object({
  type: types.string(),
  keys: z.record(z.string(), ReceiptVerificationKey$inboundSchema),
});

export function receiptVerificationKeyHistoryFromJSON(
  jsonString: string,
): SafeParseResult<ReceiptVerificationKeyHistory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReceiptVerificationKeyHistory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceiptVerificationKeyHistory' from JSON`,
  );
}
