/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8cfcf4d7ab56
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smart-union.js";
import {
  HTTPMethodEnum,
  HTTPMethodEnum$outboundSchema,
} from "./http-method-enum.js";
import {
  PriceInput,
  PriceInput$Outbound,
  PriceInput$outboundSchema,
} from "./price-input.js";
import {
  ResourceInputFulfillmentModeEnum,
  ResourceInputFulfillmentModeEnum$outboundSchema,
} from "./resource-input-fulfillment-mode-enum.js";

/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
 */
export const ResourceVersionCreateFeeMode = {
  BuyerPays: "buyer_pays",
  TenantAbsorbsUpToCap: "tenant_absorbs_up_to_cap",
} as const;
/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
 */
export type ResourceVersionCreateFeeMode = ClosedEnum<
  typeof ResourceVersionCreateFeeMode
>;

/**
 * * `USD` - USD
 */
export const ResourceVersionCreateQuoteCurrency = {
  Usd: "USD",
} as const;
/**
 * * `USD` - USD
 */
export type ResourceVersionCreateQuoteCurrency = ClosedEnum<
  typeof ResourceVersionCreateQuoteCurrency
>;

/**
 * Provider-neutral paid-entitlement fulfillment.
 */
export type ResourceVersionCreateFulfillmentConfig3 = {
  entitlementKey: string;
  quantityAtomic: string;
  provisionerAdapterId: string;
};

/**
 * Signed-webhook fulfillment.
 */
export type ResourceVersionCreateFulfillmentConfig2 = {
  webhookEndpointId: string;
};

/**
 * Static fulfillment; the object must be empty.
 */
export type ResourceVersionCreateFulfillmentConfig1 = {};

export type ResourceVersionCreateFulfillmentConfig =
  | ResourceVersionCreateFulfillmentConfig3
  | ResourceVersionCreateFulfillmentConfig2
  | ResourceVersionCreateFulfillmentConfig1;

export type ResourceVersionCreate = {
  feeMode?: ResourceVersionCreateFeeMode | undefined;
  quoteCurrency?: ResourceVersionCreateQuoteCurrency | undefined;
  feeAllowanceCapQuoteMicros?: string | undefined;
  expectedLatestVersion: number;
  /**
   * * `GET` - GET
   *
   * @remarks
   * * `POST` - POST
   * * `PUT` - PUT
   * * `PATCH` - PATCH
   * * `DELETE` - DELETE
   */
  method: HTTPMethodEnum;
  path: string;
  description: string;
  mimeType?: string | undefined;
  /**
   * * `webhook` - webhook
   *
   * @remarks
   * * `static` - static
   * * `entitlement` - entitlement
   */
  fulfillmentMode: ResourceInputFulfillmentModeEnum;
  fulfillmentConfig?:
    | ResourceVersionCreateFulfillmentConfig3
    | ResourceVersionCreateFulfillmentConfig2
    | ResourceVersionCreateFulfillmentConfig1
    | undefined;
  prices: Array<PriceInput>;
};

/** @internal */
export const ResourceVersionCreateFeeMode$outboundSchema: z.ZodMiniEnum<
  typeof ResourceVersionCreateFeeMode
> = z.enum(ResourceVersionCreateFeeMode);

/** @internal */
export const ResourceVersionCreateQuoteCurrency$outboundSchema: z.ZodMiniEnum<
  typeof ResourceVersionCreateQuoteCurrency
> = z.enum(ResourceVersionCreateQuoteCurrency);

/** @internal */
export type ResourceVersionCreateFulfillmentConfig3$Outbound = {
  entitlement_key: string;
  quantity_atomic: string;
  provisioner_adapter_id: string;
};

/** @internal */
export const ResourceVersionCreateFulfillmentConfig3$outboundSchema:
  z.ZodMiniType<
    ResourceVersionCreateFulfillmentConfig3$Outbound,
    ResourceVersionCreateFulfillmentConfig3
  > = z.pipe(
    z.object({
      entitlementKey: z.string(),
      quantityAtomic: z.string(),
      provisionerAdapterId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        entitlementKey: "entitlement_key",
        quantityAtomic: "quantity_atomic",
        provisionerAdapterId: "provisioner_adapter_id",
      });
    }),
  );

export function resourceVersionCreateFulfillmentConfig3ToJSON(
  resourceVersionCreateFulfillmentConfig3:
    ResourceVersionCreateFulfillmentConfig3,
): string {
  return JSON.stringify(
    ResourceVersionCreateFulfillmentConfig3$outboundSchema.parse(
      resourceVersionCreateFulfillmentConfig3,
    ),
  );
}

/** @internal */
export type ResourceVersionCreateFulfillmentConfig2$Outbound = {
  webhook_endpoint_id: string;
};

/** @internal */
export const ResourceVersionCreateFulfillmentConfig2$outboundSchema:
  z.ZodMiniType<
    ResourceVersionCreateFulfillmentConfig2$Outbound,
    ResourceVersionCreateFulfillmentConfig2
  > = z.pipe(
    z.object({
      webhookEndpointId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        webhookEndpointId: "webhook_endpoint_id",
      });
    }),
  );

export function resourceVersionCreateFulfillmentConfig2ToJSON(
  resourceVersionCreateFulfillmentConfig2:
    ResourceVersionCreateFulfillmentConfig2,
): string {
  return JSON.stringify(
    ResourceVersionCreateFulfillmentConfig2$outboundSchema.parse(
      resourceVersionCreateFulfillmentConfig2,
    ),
  );
}

/** @internal */
export type ResourceVersionCreateFulfillmentConfig1$Outbound = {};

/** @internal */
export const ResourceVersionCreateFulfillmentConfig1$outboundSchema:
  z.ZodMiniType<
    ResourceVersionCreateFulfillmentConfig1$Outbound,
    ResourceVersionCreateFulfillmentConfig1
  > = z.object({});

export function resourceVersionCreateFulfillmentConfig1ToJSON(
  resourceVersionCreateFulfillmentConfig1:
    ResourceVersionCreateFulfillmentConfig1,
): string {
  return JSON.stringify(
    ResourceVersionCreateFulfillmentConfig1$outboundSchema.parse(
      resourceVersionCreateFulfillmentConfig1,
    ),
  );
}

/** @internal */
export type ResourceVersionCreateFulfillmentConfig$Outbound =
  | ResourceVersionCreateFulfillmentConfig3$Outbound
  | ResourceVersionCreateFulfillmentConfig2$Outbound
  | ResourceVersionCreateFulfillmentConfig1$Outbound;

/** @internal */
export const ResourceVersionCreateFulfillmentConfig$outboundSchema:
  z.ZodMiniType<
    ResourceVersionCreateFulfillmentConfig$Outbound,
    ResourceVersionCreateFulfillmentConfig
  > = smartUnion([
    z.lazy(() => ResourceVersionCreateFulfillmentConfig3$outboundSchema),
    z.lazy(() => ResourceVersionCreateFulfillmentConfig2$outboundSchema),
    z.lazy(() => ResourceVersionCreateFulfillmentConfig1$outboundSchema),
  ]);

export function resourceVersionCreateFulfillmentConfigToJSON(
  resourceVersionCreateFulfillmentConfig:
    ResourceVersionCreateFulfillmentConfig,
): string {
  return JSON.stringify(
    ResourceVersionCreateFulfillmentConfig$outboundSchema.parse(
      resourceVersionCreateFulfillmentConfig,
    ),
  );
}

/** @internal */
export type ResourceVersionCreate$Outbound = {
  fee_mode: string;
  quote_currency: string;
  fee_allowance_cap_quote_micros: string;
  expected_latest_version: number;
  method: string;
  path: string;
  description: string;
  mime_type: string;
  fulfillment_mode: string;
  fulfillment_config?:
    | ResourceVersionCreateFulfillmentConfig3$Outbound
    | ResourceVersionCreateFulfillmentConfig2$Outbound
    | ResourceVersionCreateFulfillmentConfig1$Outbound
    | undefined;
  prices: Array<PriceInput$Outbound>;
};

/** @internal */
export const ResourceVersionCreate$outboundSchema: z.ZodMiniType<
  ResourceVersionCreate$Outbound,
  ResourceVersionCreate
> = z.pipe(
  z.object({
    feeMode: z._default(
      ResourceVersionCreateFeeMode$outboundSchema,
      "buyer_pays",
    ),
    quoteCurrency: z._default(
      ResourceVersionCreateQuoteCurrency$outboundSchema,
      "USD",
    ),
    feeAllowanceCapQuoteMicros: z._default(z.string(), "0"),
    expectedLatestVersion: z.int(),
    method: HTTPMethodEnum$outboundSchema,
    path: z.string(),
    description: z.string(),
    mimeType: z._default(z.string(), "application/json"),
    fulfillmentMode: ResourceInputFulfillmentModeEnum$outboundSchema,
    fulfillmentConfig: z.optional(smartUnion([
      z.lazy(() => ResourceVersionCreateFulfillmentConfig3$outboundSchema),
      z.lazy(() => ResourceVersionCreateFulfillmentConfig2$outboundSchema),
      z.lazy(() => ResourceVersionCreateFulfillmentConfig1$outboundSchema),
    ])),
    prices: z.array(PriceInput$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      feeMode: "fee_mode",
      quoteCurrency: "quote_currency",
      feeAllowanceCapQuoteMicros: "fee_allowance_cap_quote_micros",
      expectedLatestVersion: "expected_latest_version",
      mimeType: "mime_type",
      fulfillmentMode: "fulfillment_mode",
      fulfillmentConfig: "fulfillment_config",
    });
  }),
);

export function resourceVersionCreateToJSON(
  resourceVersionCreate: ResourceVersionCreate,
): string {
  return JSON.stringify(
    ResourceVersionCreate$outboundSchema.parse(resourceVersionCreate),
  );
}
