/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 899813b5f09c
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { smartUnion } from "../types/smart-union.js";
import {
  HTTPMethodEnum,
  HTTPMethodEnum$outboundSchema,
} from "./http-method-enum.js";
import {
  PriceInput,
  PriceInput$Outbound,
  PriceInput$outboundSchema,
} from "./price-input.js";
import {
  ResourceInputFulfillmentModeEnum,
  ResourceInputFulfillmentModeEnum$outboundSchema,
} from "./resource-input-fulfillment-mode-enum.js";

/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
 */
export const ResourceCreateFeeMode = {
  BuyerPays: "buyer_pays",
  TenantAbsorbsUpToCap: "tenant_absorbs_up_to_cap",
} as const;
/**
 * * `buyer_pays` - buyer_pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - tenant_absorbs_up_to_cap
 */
export type ResourceCreateFeeMode = ClosedEnum<typeof ResourceCreateFeeMode>;

/**
 * * `USD` - USD
 */
export const ResourceCreateQuoteCurrency = {
  Usd: "USD",
} as const;
/**
 * * `USD` - USD
 */
export type ResourceCreateQuoteCurrency = ClosedEnum<
  typeof ResourceCreateQuoteCurrency
>;

/**
 * Provider-neutral paid-entitlement fulfillment.
 */
export type FulfillmentConfig3 = {
  entitlementKey: string;
  quantityAtomic: string;
  provisionerAdapterId: string;
};

/**
 * Signed-webhook fulfillment.
 */
export type FulfillmentConfig2 = {
  webhookEndpointId: string;
};

/**
 * Static fulfillment; the object must be empty.
 */
export type FulfillmentConfig1 = {};

export type ResourceCreateFulfillmentConfig =
  | FulfillmentConfig3
  | FulfillmentConfig2
  | FulfillmentConfig1;

export type ResourceCreate = {
  feeMode?: ResourceCreateFeeMode | undefined;
  quoteCurrency?: ResourceCreateQuoteCurrency | undefined;
  feeAllowanceCapQuoteMicros?: string | undefined;
  key: string;
  name: string;
  /**
   * * `GET` - GET
   *
   * @remarks
   * * `POST` - POST
   * * `PUT` - PUT
   * * `PATCH` - PATCH
   * * `DELETE` - DELETE
   */
  method: HTTPMethodEnum;
  path: string;
  description: string;
  mimeType?: string | undefined;
  /**
   * * `webhook` - webhook
   *
   * @remarks
   * * `static` - static
   * * `entitlement` - entitlement
   */
  fulfillmentMode: ResourceInputFulfillmentModeEnum;
  fulfillmentConfig?:
    | FulfillmentConfig3
    | FulfillmentConfig2
    | FulfillmentConfig1
    | undefined;
  prices: Array<PriceInput>;
};

/** @internal */
export const ResourceCreateFeeMode$outboundSchema: z.ZodMiniEnum<
  typeof ResourceCreateFeeMode
> = z.enum(ResourceCreateFeeMode);

/** @internal */
export const ResourceCreateQuoteCurrency$outboundSchema: z.ZodMiniEnum<
  typeof ResourceCreateQuoteCurrency
> = z.enum(ResourceCreateQuoteCurrency);

/** @internal */
export type FulfillmentConfig3$Outbound = {
  entitlement_key: string;
  quantity_atomic: string;
  provisioner_adapter_id: string;
};

/** @internal */
export const FulfillmentConfig3$outboundSchema: z.ZodMiniType<
  FulfillmentConfig3$Outbound,
  FulfillmentConfig3
> = z.pipe(
  z.object({
    entitlementKey: z.string(),
    quantityAtomic: z.string(),
    provisionerAdapterId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      entitlementKey: "entitlement_key",
      quantityAtomic: "quantity_atomic",
      provisionerAdapterId: "provisioner_adapter_id",
    });
  }),
);

export function fulfillmentConfig3ToJSON(
  fulfillmentConfig3: FulfillmentConfig3,
): string {
  return JSON.stringify(
    FulfillmentConfig3$outboundSchema.parse(fulfillmentConfig3),
  );
}

/** @internal */
export type FulfillmentConfig2$Outbound = {
  webhook_endpoint_id: string;
};

/** @internal */
export const FulfillmentConfig2$outboundSchema: z.ZodMiniType<
  FulfillmentConfig2$Outbound,
  FulfillmentConfig2
> = z.pipe(
  z.object({
    webhookEndpointId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      webhookEndpointId: "webhook_endpoint_id",
    });
  }),
);

export function fulfillmentConfig2ToJSON(
  fulfillmentConfig2: FulfillmentConfig2,
): string {
  return JSON.stringify(
    FulfillmentConfig2$outboundSchema.parse(fulfillmentConfig2),
  );
}

/** @internal */
export type FulfillmentConfig1$Outbound = {};

/** @internal */
export const FulfillmentConfig1$outboundSchema: z.ZodMiniType<
  FulfillmentConfig1$Outbound,
  FulfillmentConfig1
> = z.object({});

export function fulfillmentConfig1ToJSON(
  fulfillmentConfig1: FulfillmentConfig1,
): string {
  return JSON.stringify(
    FulfillmentConfig1$outboundSchema.parse(fulfillmentConfig1),
  );
}

/** @internal */
export type ResourceCreateFulfillmentConfig$Outbound =
  | FulfillmentConfig3$Outbound
  | FulfillmentConfig2$Outbound
  | FulfillmentConfig1$Outbound;

/** @internal */
export const ResourceCreateFulfillmentConfig$outboundSchema: z.ZodMiniType<
  ResourceCreateFulfillmentConfig$Outbound,
  ResourceCreateFulfillmentConfig
> = smartUnion([
  z.lazy(() => FulfillmentConfig3$outboundSchema),
  z.lazy(() => FulfillmentConfig2$outboundSchema),
  z.lazy(() => FulfillmentConfig1$outboundSchema),
]);

export function resourceCreateFulfillmentConfigToJSON(
  resourceCreateFulfillmentConfig: ResourceCreateFulfillmentConfig,
): string {
  return JSON.stringify(
    ResourceCreateFulfillmentConfig$outboundSchema.parse(
      resourceCreateFulfillmentConfig,
    ),
  );
}

/** @internal */
export type ResourceCreate$Outbound = {
  fee_mode: string;
  quote_currency: string;
  fee_allowance_cap_quote_micros: string;
  key: string;
  name: string;
  method: string;
  path: string;
  description: string;
  mime_type: string;
  fulfillment_mode: string;
  fulfillment_config?:
    | FulfillmentConfig3$Outbound
    | FulfillmentConfig2$Outbound
    | FulfillmentConfig1$Outbound
    | undefined;
  prices: Array<PriceInput$Outbound>;
};

/** @internal */
export const ResourceCreate$outboundSchema: z.ZodMiniType<
  ResourceCreate$Outbound,
  ResourceCreate
> = z.pipe(
  z.object({
    feeMode: z._default(ResourceCreateFeeMode$outboundSchema, "buyer_pays"),
    quoteCurrency: z._default(
      ResourceCreateQuoteCurrency$outboundSchema,
      "USD",
    ),
    feeAllowanceCapQuoteMicros: z._default(z.string(), "0"),
    key: z.string(),
    name: z.string(),
    method: HTTPMethodEnum$outboundSchema,
    path: z.string(),
    description: z.string(),
    mimeType: z._default(z.string(), "application/json"),
    fulfillmentMode: ResourceInputFulfillmentModeEnum$outboundSchema,
    fulfillmentConfig: z.optional(
      smartUnion([
        z.lazy(() => FulfillmentConfig3$outboundSchema),
        z.lazy(() => FulfillmentConfig2$outboundSchema),
        z.lazy(() => FulfillmentConfig1$outboundSchema),
      ]),
    ),
    prices: z.array(PriceInput$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      feeMode: "fee_mode",
      quoteCurrency: "quote_currency",
      feeAllowanceCapQuoteMicros: "fee_allowance_cap_quote_micros",
      mimeType: "mime_type",
      fulfillmentMode: "fulfillment_mode",
      fulfillmentConfig: "fulfillment_config",
    });
  }),
);

export function resourceCreateToJSON(resourceCreate: ResourceCreate): string {
  return JSON.stringify(ResourceCreate$outboundSchema.parse(resourceCreate));
}
