/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1868cd810195
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ResourceVersionRetireExpectedStateEnum,
  ResourceVersionRetireExpectedStateEnum$outboundSchema,
} from "./resource-version-retire-expected-state-enum.js";

export type ResourceVersionRetire = {
  expectedVersion: number;
  /**
   * * `draft` - draft
   *
   * @remarks
   * * `active` - active
   */
  expectedState: ResourceVersionRetireExpectedStateEnum;
};

/** @internal */
export type ResourceVersionRetire$Outbound = {
  expected_version: number;
  expected_state: string;
};

/** @internal */
export const ResourceVersionRetire$outboundSchema: z.ZodMiniType<
  ResourceVersionRetire$Outbound,
  ResourceVersionRetire
> = z.pipe(
  z.object({
    expectedVersion: z.int(),
    expectedState: ResourceVersionRetireExpectedStateEnum$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      expectedVersion: "expected_version",
      expectedState: "expected_state",
    });
  }),
);

export function resourceVersionRetireToJSON(
  resourceVersionRetire: ResourceVersionRetire,
): string {
  return JSON.stringify(
    ResourceVersionRetire$outboundSchema.parse(resourceVersionRetire),
  );
}
