/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 29a11c7395cf
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ResourcePrice,
  ResourcePrice$inboundSchema,
} from "./resource-price.js";

/**
 * * `proxy` - Reverse proxy
 *
 * @remarks
 * * `webhook` - Signed webhook
 * * `static` - Static response
 * * `entitlement` - Paid entitlement
 */
export const FulfillmentMode = {
  Proxy: "proxy",
  Webhook: "webhook",
  Static: "static",
  Entitlement: "entitlement",
} as const;
/**
 * * `proxy` - Reverse proxy
 *
 * @remarks
 * * `webhook` - Signed webhook
 * * `static` - Static response
 * * `entitlement` - Paid entitlement
 */
export type FulfillmentMode = OpenEnum<typeof FulfillmentMode>;

/**
 * Provider-neutral paid-entitlement fulfillment.
 */
export type Three = {
  entitlementKey: string;
  quantityAtomic: string;
  provisionerAdapterId: string;
};

/**
 * Signed-webhook fulfillment.
 */
export type Two = {
  webhookEndpointId: string;
};

/**
 * Static fulfillment; the object must be empty.
 */
export type One = {};

export type FulfillmentConfig = Three | Two | One;

/**
 * * `buyer_pays` - Buyer pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - Tenant absorbs up to cap
 */
export const ResourceVersionFeeMode = {
  BuyerPays: "buyer_pays",
  TenantAbsorbsUpToCap: "tenant_absorbs_up_to_cap",
} as const;
/**
 * * `buyer_pays` - Buyer pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - Tenant absorbs up to cap
 */
export type ResourceVersionFeeMode = OpenEnum<typeof ResourceVersionFeeMode>;

/**
 * * `USD` - US dollar
 */
export const ResourceVersionQuoteCurrency = {
  Usd: "USD",
} as const;
/**
 * * `USD` - US dollar
 */
export type ResourceVersionQuoteCurrency = ClosedEnum<
  typeof ResourceVersionQuoteCurrency
>;

/**
 * * `draft` - Draft
 *
 * @remarks
 * * `active` - Active
 * * `retired` - Retired
 */
export const ResourceVersionState = {
  Draft: "draft",
  Active: "active",
  Retired: "retired",
} as const;
/**
 * * `draft` - Draft
 *
 * @remarks
 * * `active` - Active
 * * `retired` - Retired
 */
export type ResourceVersionState = OpenEnum<typeof ResourceVersionState>;

export type ResourceVersion = {
  id: string;
  version: number;
  method: string;
  path: string;
  description: string;
  mimeType: string;
  fulfillmentMode: FulfillmentMode;
  fulfillmentConfig: Three | Two | One;
  feeMode: ResourceVersionFeeMode;
  quoteCurrency: ResourceVersionQuoteCurrency;
  feeAllowanceCapQuoteMicros: string;
  state: ResourceVersionState;
  prices: Array<ResourcePrice>;
};

/** @internal */
export const FulfillmentMode$inboundSchema: z.ZodMiniType<
  FulfillmentMode,
  unknown
> = openEnums.inboundSchema(FulfillmentMode);

/** @internal */
export const Three$inboundSchema: z.ZodMiniType<Three, unknown> = z.pipe(
  z.object({
    entitlement_key: types.string(),
    quantity_atomic: types.string(),
    provisioner_adapter_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "entitlement_key": "entitlementKey",
      "quantity_atomic": "quantityAtomic",
      "provisioner_adapter_id": "provisionerAdapterId",
    });
  }),
);

export function threeFromJSON(
  jsonString: string,
): SafeParseResult<Three, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Three$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Three' from JSON`,
  );
}

/** @internal */
export const Two$inboundSchema: z.ZodMiniType<Two, unknown> = z.pipe(
  z.object({
    webhook_endpoint_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "webhook_endpoint_id": "webhookEndpointId",
    });
  }),
);

export function twoFromJSON(
  jsonString: string,
): SafeParseResult<Two, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Two$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Two' from JSON`,
  );
}

/** @internal */
export const One$inboundSchema: z.ZodMiniType<One, unknown> = z.object({});

export function oneFromJSON(
  jsonString: string,
): SafeParseResult<One, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => One$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'One' from JSON`,
  );
}

/** @internal */
export const FulfillmentConfig$inboundSchema: z.ZodMiniType<
  FulfillmentConfig,
  unknown
> = smartUnion([
  z.lazy(() => Three$inboundSchema),
  z.lazy(() => Two$inboundSchema),
  z.lazy(() => One$inboundSchema),
]);

export function fulfillmentConfigFromJSON(
  jsonString: string,
): SafeParseResult<FulfillmentConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FulfillmentConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FulfillmentConfig' from JSON`,
  );
}

/** @internal */
export const ResourceVersionFeeMode$inboundSchema: z.ZodMiniType<
  ResourceVersionFeeMode,
  unknown
> = openEnums.inboundSchema(ResourceVersionFeeMode);

/** @internal */
export const ResourceVersionQuoteCurrency$inboundSchema: z.ZodMiniEnum<
  typeof ResourceVersionQuoteCurrency
> = z.enum(ResourceVersionQuoteCurrency);

/** @internal */
export const ResourceVersionState$inboundSchema: z.ZodMiniType<
  ResourceVersionState,
  unknown
> = openEnums.inboundSchema(ResourceVersionState);

/** @internal */
export const ResourceVersion$inboundSchema: z.ZodMiniType<
  ResourceVersion,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    version: types.number(),
    method: types.string(),
    path: types.string(),
    description: types.string(),
    mime_type: types.string(),
    fulfillment_mode: FulfillmentMode$inboundSchema,
    fulfillment_config: smartUnion([
      z.lazy(() => Three$inboundSchema),
      z.lazy(() => Two$inboundSchema),
      z.lazy(() => One$inboundSchema),
    ]),
    fee_mode: ResourceVersionFeeMode$inboundSchema,
    quote_currency: ResourceVersionQuoteCurrency$inboundSchema,
    fee_allowance_cap_quote_micros: types.string(),
    state: ResourceVersionState$inboundSchema,
    prices: z.array(ResourcePrice$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mime_type": "mimeType",
      "fulfillment_mode": "fulfillmentMode",
      "fulfillment_config": "fulfillmentConfig",
      "fee_mode": "feeMode",
      "quote_currency": "quoteCurrency",
      "fee_allowance_cap_quote_micros": "feeAllowanceCapQuoteMicros",
    });
  }),
);

export function resourceVersionFromJSON(
  jsonString: string,
): SafeParseResult<ResourceVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceVersion' from JSON`,
  );
}
