/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c422d76182ba
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ResourceVersionActivate = {
  expectedTargetVersion: number;
  expectedActiveVersionId: string | null;
};

/** @internal */
export type ResourceVersionActivate$Outbound = {
  expected_target_version: number;
  expected_active_version_id: string | null;
};

/** @internal */
export const ResourceVersionActivate$outboundSchema: z.ZodMiniType<
  ResourceVersionActivate$Outbound,
  ResourceVersionActivate
> = z.pipe(
  z.object({
    expectedTargetVersion: z.int(),
    expectedActiveVersionId: z.nullable(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      expectedTargetVersion: "expected_target_version",
      expectedActiveVersionId: "expected_active_version_id",
    });
  }),
);

export function resourceVersionActivateToJSON(
  resourceVersionActivate: ResourceVersionActivate,
): string {
  return JSON.stringify(
    ResourceVersionActivate$outboundSchema.parse(resourceVersionActivate),
  );
}
