/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: caa57b149939
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ResourcePrice = {
  assetId: string;
  network: string;
  contractAddress: string;
  displayName: string;
  symbol: string;
  decimals: number;
  walletId: string;
  walletVersionId: string;
  recipient: string;
  amountAtomic: string;
  listedAmountAtomic: string;
  maxTimeoutSeconds: number;
};

/** @internal */
export const ResourcePrice$inboundSchema: z.ZodMiniType<
  ResourcePrice,
  unknown
> = z.pipe(
  z.object({
    asset_id: types.string(),
    network: types.string(),
    contract_address: types.string(),
    display_name: types.string(),
    symbol: types.string(),
    decimals: types.number(),
    wallet_id: types.string(),
    wallet_version_id: types.string(),
    recipient: types.string(),
    amount_atomic: types.string(),
    listed_amount_atomic: types.string(),
    max_timeout_seconds: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "contract_address": "contractAddress",
      "display_name": "displayName",
      "wallet_id": "walletId",
      "wallet_version_id": "walletVersionId",
      "amount_atomic": "amountAtomic",
      "listed_amount_atomic": "listedAmountAtomic",
      "max_timeout_seconds": "maxTimeoutSeconds",
    });
  }),
);

export function resourcePriceFromJSON(
  jsonString: string,
): SafeParseResult<ResourcePrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourcePrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourcePrice' from JSON`,
  );
}
