/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0c69c7847a39
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ResourcePrice,
  ResourcePrice$inboundSchema,
} from "./resource-price.js";
import {
  ResourceVersion,
  ResourceVersion$inboundSchema,
} from "./resource-version.js";

/**
 * * `proxy` - Reverse proxy
 *
 * @remarks
 * * `webhook` - Signed webhook
 * * `static` - Static response
 * * `entitlement` - Paid entitlement
 */
export const ResourceFulfillmentMode = {
  Proxy: "proxy",
  Webhook: "webhook",
  Static: "static",
  Entitlement: "entitlement",
} as const;
/**
 * * `proxy` - Reverse proxy
 *
 * @remarks
 * * `webhook` - Signed webhook
 * * `static` - Static response
 * * `entitlement` - Paid entitlement
 */
export type ResourceFulfillmentMode = OpenEnum<typeof ResourceFulfillmentMode>;

/**
 * Provider-neutral paid-entitlement fulfillment.
 */
export type ResourceFulfillmentConfig3 = {
  entitlementKey: string;
  quantityAtomic: string;
  provisionerAdapterId: string;
};

/**
 * Signed-webhook fulfillment.
 */
export type ResourceFulfillmentConfig2 = {
  webhookEndpointId: string;
};

/**
 * Static fulfillment; the object must be empty.
 */
export type ResourceFulfillmentConfig1 = {};

export type ResourceFulfillmentConfig =
  | ResourceFulfillmentConfig3
  | ResourceFulfillmentConfig2
  | ResourceFulfillmentConfig1;

/**
 * * `buyer_pays` - Buyer pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - Tenant absorbs up to cap
 */
export const ResourceFeeMode = {
  BuyerPays: "buyer_pays",
  TenantAbsorbsUpToCap: "tenant_absorbs_up_to_cap",
} as const;
/**
 * * `buyer_pays` - Buyer pays
 *
 * @remarks
 * * `tenant_absorbs_up_to_cap` - Tenant absorbs up to cap
 */
export type ResourceFeeMode = OpenEnum<typeof ResourceFeeMode>;

/**
 * * `USD` - US dollar
 */
export const ResourceQuoteCurrency = {
  Usd: "USD",
} as const;
/**
 * * `USD` - US dollar
 */
export type ResourceQuoteCurrency = ClosedEnum<typeof ResourceQuoteCurrency>;

/**
 * * `draft` - Draft
 *
 * @remarks
 * * `active` - Active
 * * `retired` - Retired
 */
export const ResourceState = {
  Draft: "draft",
  Active: "active",
  Retired: "retired",
} as const;
/**
 * * `draft` - Draft
 *
 * @remarks
 * * `active` - Active
 * * `retired` - Retired
 */
export type ResourceState = OpenEnum<typeof ResourceState>;

export type ActiveVersion = {
  id: string;
  version: number;
  method: string;
  path: string;
  description: string;
  mimeType: string;
  fulfillmentMode: ResourceFulfillmentMode;
  fulfillmentConfig:
    | ResourceFulfillmentConfig3
    | ResourceFulfillmentConfig2
    | ResourceFulfillmentConfig1;
  feeMode: ResourceFeeMode;
  quoteCurrency: ResourceQuoteCurrency;
  feeAllowanceCapQuoteMicros: string;
  state: ResourceState;
  prices: Array<ResourcePrice>;
};

export type Resource = {
  id: string;
  publicPaymentId: string;
  key: string;
  name: string;
  activeVersion: ActiveVersion | null;
  versions: Array<ResourceVersion>;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const ResourceFulfillmentMode$inboundSchema: z.ZodMiniType<
  ResourceFulfillmentMode,
  unknown
> = openEnums.inboundSchema(ResourceFulfillmentMode);

/** @internal */
export const ResourceFulfillmentConfig3$inboundSchema: z.ZodMiniType<
  ResourceFulfillmentConfig3,
  unknown
> = z.pipe(
  z.object({
    entitlement_key: types.string(),
    quantity_atomic: types.string(),
    provisioner_adapter_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "entitlement_key": "entitlementKey",
      "quantity_atomic": "quantityAtomic",
      "provisioner_adapter_id": "provisionerAdapterId",
    });
  }),
);

export function resourceFulfillmentConfig3FromJSON(
  jsonString: string,
): SafeParseResult<ResourceFulfillmentConfig3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceFulfillmentConfig3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceFulfillmentConfig3' from JSON`,
  );
}

/** @internal */
export const ResourceFulfillmentConfig2$inboundSchema: z.ZodMiniType<
  ResourceFulfillmentConfig2,
  unknown
> = z.pipe(
  z.object({
    webhook_endpoint_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "webhook_endpoint_id": "webhookEndpointId",
    });
  }),
);

export function resourceFulfillmentConfig2FromJSON(
  jsonString: string,
): SafeParseResult<ResourceFulfillmentConfig2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceFulfillmentConfig2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceFulfillmentConfig2' from JSON`,
  );
}

/** @internal */
export const ResourceFulfillmentConfig1$inboundSchema: z.ZodMiniType<
  ResourceFulfillmentConfig1,
  unknown
> = z.object({});

export function resourceFulfillmentConfig1FromJSON(
  jsonString: string,
): SafeParseResult<ResourceFulfillmentConfig1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceFulfillmentConfig1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceFulfillmentConfig1' from JSON`,
  );
}

/** @internal */
export const ResourceFulfillmentConfig$inboundSchema: z.ZodMiniType<
  ResourceFulfillmentConfig,
  unknown
> = smartUnion([
  z.lazy(() => ResourceFulfillmentConfig3$inboundSchema),
  z.lazy(() => ResourceFulfillmentConfig2$inboundSchema),
  z.lazy(() => ResourceFulfillmentConfig1$inboundSchema),
]);

export function resourceFulfillmentConfigFromJSON(
  jsonString: string,
): SafeParseResult<ResourceFulfillmentConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceFulfillmentConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceFulfillmentConfig' from JSON`,
  );
}

/** @internal */
export const ResourceFeeMode$inboundSchema: z.ZodMiniType<
  ResourceFeeMode,
  unknown
> = openEnums.inboundSchema(ResourceFeeMode);

/** @internal */
export const ResourceQuoteCurrency$inboundSchema: z.ZodMiniEnum<
  typeof ResourceQuoteCurrency
> = z.enum(ResourceQuoteCurrency);

/** @internal */
export const ResourceState$inboundSchema: z.ZodMiniType<
  ResourceState,
  unknown
> = openEnums.inboundSchema(ResourceState);

/** @internal */
export const ActiveVersion$inboundSchema: z.ZodMiniType<
  ActiveVersion,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    version: types.number(),
    method: types.string(),
    path: types.string(),
    description: types.string(),
    mime_type: types.string(),
    fulfillment_mode: ResourceFulfillmentMode$inboundSchema,
    fulfillment_config: smartUnion([
      z.lazy(() => ResourceFulfillmentConfig3$inboundSchema),
      z.lazy(() => ResourceFulfillmentConfig2$inboundSchema),
      z.lazy(() => ResourceFulfillmentConfig1$inboundSchema),
    ]),
    fee_mode: ResourceFeeMode$inboundSchema,
    quote_currency: ResourceQuoteCurrency$inboundSchema,
    fee_allowance_cap_quote_micros: types.string(),
    state: ResourceState$inboundSchema,
    prices: z.array(ResourcePrice$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mime_type": "mimeType",
      "fulfillment_mode": "fulfillmentMode",
      "fulfillment_config": "fulfillmentConfig",
      "fee_mode": "feeMode",
      "quote_currency": "quoteCurrency",
      "fee_allowance_cap_quote_micros": "feeAllowanceCapQuoteMicros",
    });
  }),
);

export function activeVersionFromJSON(
  jsonString: string,
): SafeParseResult<ActiveVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActiveVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActiveVersion' from JSON`,
  );
}

/** @internal */
export const Resource$inboundSchema: z.ZodMiniType<Resource, unknown> = z.pipe(
  z.object({
    id: types.string(),
    public_payment_id: types.string(),
    key: types.string(),
    name: types.string(),
    active_version: types.nullable(z.lazy(() => ActiveVersion$inboundSchema)),
    versions: z.array(ResourceVersion$inboundSchema),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "public_payment_id": "publicPaymentId",
      "active_version": "activeVersion",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function resourceFromJSON(
  jsonString: string,
): SafeParseResult<Resource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Resource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Resource' from JSON`,
  );
}
