/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 16dbcbe31fff
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `draft` - draft
 *
 * @remarks
 * * `active` - active
 */
export const ResourceVersionRetireExpectedStateEnum = {
  Draft: "draft",
  Active: "active",
} as const;
/**
 * * `draft` - draft
 *
 * @remarks
 * * `active` - active
 */
export type ResourceVersionRetireExpectedStateEnum = ClosedEnum<
  typeof ResourceVersionRetireExpectedStateEnum
>;

/** @internal */
export const ResourceVersionRetireExpectedStateEnum$outboundSchema:
  z.ZodMiniEnum<typeof ResourceVersionRetireExpectedStateEnum> = z.enum(
    ResourceVersionRetireExpectedStateEnum,
  );
