/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 525b5153f54d
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * * `webhook` - webhook
 *
 * @remarks
 * * `static` - static
 * * `entitlement` - entitlement
 */
export const ResourceInputFulfillmentModeEnum = {
  Webhook: "webhook",
  Static: "static",
  Entitlement: "entitlement",
} as const;
/**
 * * `webhook` - webhook
 *
 * @remarks
 * * `static` - static
 * * `entitlement` - entitlement
 */
export type ResourceInputFulfillmentModeEnum = ClosedEnum<
  typeof ResourceInputFulfillmentModeEnum
>;

/** @internal */
export const ResourceInputFulfillmentModeEnum$outboundSchema: z.ZodMiniEnum<
  typeof ResourceInputFulfillmentModeEnum
> = z.enum(ResourceInputFulfillmentModeEnum);
