/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cd7743089b76
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TenantPaymentFulfillmentProjectionStatusEnum,
  TenantPaymentFulfillmentProjectionStatusEnum$inboundSchema,
} from "./tenant-payment-fulfillment-projection-status-enum.js";
import {
  TenantPaymentReceiptProjectionStatusEnum,
  TenantPaymentReceiptProjectionStatusEnum$inboundSchema,
} from "./tenant-payment-receipt-projection-status-enum.js";
import {
  TenantPaymentScreeningSubjectProjection,
  TenantPaymentScreeningSubjectProjection$inboundSchema,
} from "./tenant-payment-screening-subject-projection.js";

/**
 * * `created` - Created
 *
 * @remarks
 * * `verifying` - Verifying
 * * `verified` - Verified
 * * `reserved` - Reserved
 * * `broadcasting` - Broadcasting
 * * `broadcast_unknown` - Broadcast unknown
 * * `broadcast` - Broadcast
 * * `confirming` - Confirming
 * * `confirmed` - Confirmed
 * * `finalized` - Finalized
 * * `rejected` - Rejected
 * * `failed` - Failed
 * * `expired` - Expired
 * * `reverted` - Reverted
 * * `reorged` - Reorged
 * * `late_confirmed` - Late confirmed
 * * `manual_review` - Manual review
 */
export const SettlementJobState = {
  Created: "created",
  Verifying: "verifying",
  Verified: "verified",
  Reserved: "reserved",
  Broadcasting: "broadcasting",
  BroadcastUnknown: "broadcast_unknown",
  Broadcast: "broadcast",
  Confirming: "confirming",
  Confirmed: "confirmed",
  Finalized: "finalized",
  Rejected: "rejected",
  Failed: "failed",
  Expired: "expired",
  Reverted: "reverted",
  Reorged: "reorged",
  LateConfirmed: "late_confirmed",
  ManualReview: "manual_review",
} as const;
/**
 * * `created` - Created
 *
 * @remarks
 * * `verifying` - Verifying
 * * `verified` - Verified
 * * `reserved` - Reserved
 * * `broadcasting` - Broadcasting
 * * `broadcast_unknown` - Broadcast unknown
 * * `broadcast` - Broadcast
 * * `confirming` - Confirming
 * * `confirmed` - Confirmed
 * * `finalized` - Finalized
 * * `rejected` - Rejected
 * * `failed` - Failed
 * * `expired` - Expired
 * * `reverted` - Reverted
 * * `reorged` - Reorged
 * * `late_confirmed` - Late confirmed
 * * `manual_review` - Manual review
 */
export type SettlementJobState = OpenEnum<typeof SettlementJobState>;

export type SettlementJobOrder = {
  id: string;
  status: string;
  buyerPaymentIdentifier: string | null;
  paidAt: Date | null;
  fulfilledAt: Date | null;
};

export type SettlementJobResource = {
  id: string;
  key: string;
  name: string;
  version: number;
  method: string;
  path: string;
  description: string;
  fulfillmentMode: string;
};

export type Asset = {
  network: string;
  contractAddress: string;
  amountAtomic: string;
  recipient: string;
};

export type Chain = {
  state: string;
  transactionHash: string;
  blockNumber: string | null;
  blockHash: string;
  confirmations: number;
  confirmationsRequired: number;
  observedAt: Date | null;
};

export type Receipt = {
  /**
   * * `not_issued` - not_issued
   *
   * @remarks
   * * `issued` - issued
   * * `integrity_failure` - integrity_failure
   */
  status: TenantPaymentReceiptProjectionStatusEnum;
  id: string | null;
  receiptDigest: string;
  signingKeyVersion: string;
  createdAt: Date | null;
};

export type Screening = {
  evaluatedAt: Date;
  buyer: TenantPaymentScreeningSubjectProjection;
  recipient: TenantPaymentScreeningSubjectProjection;
};

export type Fulfillment = {
  /**
   * * `not_created` - not_created
   *
   * @remarks
   * * `created` - created
   */
  status: TenantPaymentFulfillmentProjectionStatusEnum;
  id: string | null;
  mode: string;
  state: string;
  attemptCount: number;
  lastErrorCode: string;
  completedAt: Date | null;
};

export type SettlementJob = {
  id: string;
  orderId: string;
  reservationId: string;
  state: SettlementJobState;
  network: string;
  transactionHash: string;
  originalTransactionHash: string;
  replacedByHash: string;
  gasExecutionState: string;
  gasExecutionSequence: number;
  gasExecutionMaterialDigest: string;
  gasExecutionObservedAt: Date | null;
  payer: string;
  lastErrorCode: string;
  broadcastAttemptCount: number;
  settlementResult: any | null;
  confirmedAt: Date | null;
  finalizedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  order: SettlementJobOrder;
  resource: SettlementJobResource;
  asset: Asset;
  chain: Chain;
  receipt: Receipt;
  screening: Screening;
  fulfillment: Fulfillment;
};

/** @internal */
export const SettlementJobState$inboundSchema: z.ZodMiniType<
  SettlementJobState,
  unknown
> = openEnums.inboundSchema(SettlementJobState);

/** @internal */
export const SettlementJobOrder$inboundSchema: z.ZodMiniType<
  SettlementJobOrder,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    status: types.string(),
    buyer_payment_identifier: types.nullable(types.string()),
    paid_at: types.nullable(types.date()),
    fulfilled_at: types.nullable(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "buyer_payment_identifier": "buyerPaymentIdentifier",
      "paid_at": "paidAt",
      "fulfilled_at": "fulfilledAt",
    });
  }),
);

export function settlementJobOrderFromJSON(
  jsonString: string,
): SafeParseResult<SettlementJobOrder, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettlementJobOrder$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettlementJobOrder' from JSON`,
  );
}

/** @internal */
export const SettlementJobResource$inboundSchema: z.ZodMiniType<
  SettlementJobResource,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    key: types.string(),
    name: types.string(),
    version: types.number(),
    method: types.string(),
    path: types.string(),
    description: types.string(),
    fulfillment_mode: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "fulfillment_mode": "fulfillmentMode",
    });
  }),
);

export function settlementJobResourceFromJSON(
  jsonString: string,
): SafeParseResult<SettlementJobResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettlementJobResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettlementJobResource' from JSON`,
  );
}

/** @internal */
export const Asset$inboundSchema: z.ZodMiniType<Asset, unknown> = z.pipe(
  z.object({
    network: types.string(),
    contract_address: types.string(),
    amount_atomic: types.string(),
    recipient: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "contract_address": "contractAddress",
      "amount_atomic": "amountAtomic",
    });
  }),
);

export function assetFromJSON(
  jsonString: string,
): SafeParseResult<Asset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Asset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Asset' from JSON`,
  );
}

/** @internal */
export const Chain$inboundSchema: z.ZodMiniType<Chain, unknown> = z.pipe(
  z.object({
    state: types.string(),
    transaction_hash: types.string(),
    block_number: types.nullable(types.string()),
    block_hash: types.string(),
    confirmations: types.number(),
    confirmations_required: types.number(),
    observed_at: types.nullable(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_hash": "transactionHash",
      "block_number": "blockNumber",
      "block_hash": "blockHash",
      "confirmations_required": "confirmationsRequired",
      "observed_at": "observedAt",
    });
  }),
);

export function chainFromJSON(
  jsonString: string,
): SafeParseResult<Chain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Chain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Chain' from JSON`,
  );
}

/** @internal */
export const Receipt$inboundSchema: z.ZodMiniType<Receipt, unknown> = z.pipe(
  z.object({
    status: TenantPaymentReceiptProjectionStatusEnum$inboundSchema,
    id: types.nullable(types.string()),
    receipt_digest: types.string(),
    signing_key_version: types.string(),
    created_at: types.nullable(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "receipt_digest": "receiptDigest",
      "signing_key_version": "signingKeyVersion",
      "created_at": "createdAt",
    });
  }),
);

export function receiptFromJSON(
  jsonString: string,
): SafeParseResult<Receipt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Receipt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Receipt' from JSON`,
  );
}

/** @internal */
export const Screening$inboundSchema: z.ZodMiniType<Screening, unknown> = z
  .pipe(
    z.object({
      evaluated_at: types.date(),
      buyer: TenantPaymentScreeningSubjectProjection$inboundSchema,
      recipient: TenantPaymentScreeningSubjectProjection$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "evaluated_at": "evaluatedAt",
      });
    }),
  );

export function screeningFromJSON(
  jsonString: string,
): SafeParseResult<Screening, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Screening$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Screening' from JSON`,
  );
}

/** @internal */
export const Fulfillment$inboundSchema: z.ZodMiniType<Fulfillment, unknown> = z
  .pipe(
    z.object({
      status: TenantPaymentFulfillmentProjectionStatusEnum$inboundSchema,
      id: types.nullable(types.string()),
      mode: types.string(),
      state: types.string(),
      attempt_count: types.number(),
      last_error_code: types.string(),
      completed_at: types.nullable(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "attempt_count": "attemptCount",
        "last_error_code": "lastErrorCode",
        "completed_at": "completedAt",
      });
    }),
  );

export function fulfillmentFromJSON(
  jsonString: string,
): SafeParseResult<Fulfillment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fulfillment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fulfillment' from JSON`,
  );
}

/** @internal */
export const SettlementJob$inboundSchema: z.ZodMiniType<
  SettlementJob,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    order_id: types.string(),
    reservation_id: types.string(),
    state: SettlementJobState$inboundSchema,
    network: types.string(),
    transaction_hash: types.string(),
    original_transaction_hash: types.string(),
    replaced_by_hash: types.string(),
    gas_execution_state: types.string(),
    gas_execution_sequence: types.number(),
    gas_execution_material_digest: types.string(),
    gas_execution_observed_at: types.nullable(types.date()),
    payer: types.string(),
    last_error_code: types.string(),
    broadcast_attempt_count: types.number(),
    settlement_result: types.nullable(z.any()),
    confirmed_at: types.nullable(types.date()),
    finalized_at: types.nullable(types.date()),
    created_at: types.date(),
    updated_at: types.date(),
    order: z.lazy(() => SettlementJobOrder$inboundSchema),
    resource: z.lazy(() => SettlementJobResource$inboundSchema),
    asset: z.lazy(() => Asset$inboundSchema),
    chain: z.lazy(() => Chain$inboundSchema),
    receipt: z.lazy(() => Receipt$inboundSchema),
    screening: z.lazy(() => Screening$inboundSchema),
    fulfillment: z.lazy(() => Fulfillment$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "order_id": "orderId",
      "reservation_id": "reservationId",
      "transaction_hash": "transactionHash",
      "original_transaction_hash": "originalTransactionHash",
      "replaced_by_hash": "replacedByHash",
      "gas_execution_state": "gasExecutionState",
      "gas_execution_sequence": "gasExecutionSequence",
      "gas_execution_material_digest": "gasExecutionMaterialDigest",
      "gas_execution_observed_at": "gasExecutionObservedAt",
      "last_error_code": "lastErrorCode",
      "broadcast_attempt_count": "broadcastAttemptCount",
      "settlement_result": "settlementResult",
      "confirmed_at": "confirmedAt",
      "finalized_at": "finalizedAt",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function settlementJobFromJSON(
  jsonString: string,
): SafeParseResult<SettlementJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettlementJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettlementJob' from JSON`,
  );
}
