/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7e164c6bd919
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Decimal as Decimal$ } from "../types/decimal.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * * `included` - Included
 *
 * @remarks
 * * `finalized` - Finalized
 * * `reverted` - Reverted
 * * `reorged` - Reorged
 */
export const SettlementChainObservationState = {
  Included: "included",
  Finalized: "finalized",
  Reverted: "reverted",
  Reorged: "reorged",
} as const;
/**
 * * `included` - Included
 *
 * @remarks
 * * `finalized` - Finalized
 * * `reverted` - Reverted
 * * `reorged` - Reorged
 */
export type SettlementChainObservationState = OpenEnum<
  typeof SettlementChainObservationState
>;

export type SettlementChainObservation = {
  id: string;
  settlementJobId: string;
  network: string;
  transactionHash: string;
  state: SettlementChainObservationState;
  observationDigest: string;
  logIndex: number | null;
  blockNumber: Decimal$ | number | null;
  blockHash: string;
  assetContract: string;
  payer: string;
  recipient: string;
  amountAtomic: Decimal$ | number | null;
  executionSuccess: boolean | null;
  observedAt: Date;
  createdAt: Date;
};

/** @internal */
export const SettlementChainObservationState$inboundSchema: z.ZodMiniType<
  SettlementChainObservationState,
  unknown
> = openEnums.inboundSchema(SettlementChainObservationState);

/** @internal */
export const SettlementChainObservation$inboundSchema: z.ZodMiniType<
  SettlementChainObservation,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    settlement_job_id: types.string(),
    network: types.string(),
    transaction_hash: types.string(),
    state: SettlementChainObservationState$inboundSchema,
    observation_digest: types.string(),
    log_index: types.nullable(types.number()),
    block_number: types.nullable(
      z.pipe(z.string(), z.transform(v => new Decimal$(v))),
    ),
    block_hash: types.string(),
    asset_contract: types.string(),
    payer: types.string(),
    recipient: types.string(),
    amount_atomic: types.nullable(
      z.pipe(z.string(), z.transform(v => new Decimal$(v))),
    ),
    execution_success: types.nullable(types.boolean()),
    observed_at: types.date(),
    created_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "settlement_job_id": "settlementJobId",
      "transaction_hash": "transactionHash",
      "observation_digest": "observationDigest",
      "log_index": "logIndex",
      "block_number": "blockNumber",
      "block_hash": "blockHash",
      "asset_contract": "assetContract",
      "amount_atomic": "amountAtomic",
      "execution_success": "executionSuccess",
      "observed_at": "observedAt",
      "created_at": "createdAt",
    });
  }),
);

export function settlementChainObservationFromJSON(
  jsonString: string,
): SafeParseResult<SettlementChainObservation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettlementChainObservation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettlementChainObservation' from JSON`,
  );
}
