/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5178f7aea318
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SupportedKind = {
  x402Version: number;
  scheme: string;
  network: string;
  extra?: any | undefined;
};

/** @internal */
export const SupportedKind$inboundSchema: z.ZodMiniType<
  SupportedKind,
  unknown
> = z.object({
  x402Version: types.number(),
  scheme: types.string(),
  network: types.string(),
  extra: types.optional(z.any()),
});

export function supportedKindFromJSON(
  jsonString: string,
): SafeParseResult<SupportedKind, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportedKind$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportedKind' from JSON`,
  );
}
