/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5c30b93348d5
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SupportedKind,
  SupportedKind$inboundSchema,
} from "./supported-kind.js";

export type SupportedResponse = {
  kinds: Array<SupportedKind>;
  extensions: Array<string>;
  signers: { [k: string]: Array<string> };
};

/** @internal */
export const SupportedResponse$inboundSchema: z.ZodMiniType<
  SupportedResponse,
  unknown
> = z.object({
  kinds: z.array(SupportedKind$inboundSchema),
  extensions: z.array(types.string()),
  signers: z.record(z.string(), z.array(types.string())),
});

export function supportedResponseFromJSON(
  jsonString: string,
): SafeParseResult<SupportedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportedResponse' from JSON`,
  );
}
