/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3be507d3799d
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `not_issued` - not_issued
 *
 * @remarks
 * * `issued` - issued
 * * `integrity_failure` - integrity_failure
 */
export const TenantPaymentReceiptProjectionStatusEnum = {
  NotIssued: "not_issued",
  Issued: "issued",
  IntegrityFailure: "integrity_failure",
} as const;
/**
 * * `not_issued` - not_issued
 *
 * @remarks
 * * `issued` - issued
 * * `integrity_failure` - integrity_failure
 */
export type TenantPaymentReceiptProjectionStatusEnum = OpenEnum<
  typeof TenantPaymentReceiptProjectionStatusEnum
>;

/** @internal */
export const TenantPaymentReceiptProjectionStatusEnum$inboundSchema:
  z.ZodMiniType<TenantPaymentReceiptProjectionStatusEnum, unknown> = openEnums
    .inboundSchema(TenantPaymentReceiptProjectionStatusEnum);
