/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 431debb923ad
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TenantPaymentScreeningSubjectProjectionStatusEnum,
  TenantPaymentScreeningSubjectProjectionStatusEnum$inboundSchema,
} from "./tenant-payment-screening-subject-projection-status-enum.js";

export type TenantPaymentScreeningSubjectProjection = {
  /**
   * * `not_enforced` - not_enforced
   *
   * @remarks
   * * `allowed` - allowed
   * * `not_allowed` - not_allowed
   * * `unavailable` - unavailable
   */
  status: TenantPaymentScreeningSubjectProjectionStatusEnum;
};

/** @internal */
export const TenantPaymentScreeningSubjectProjection$inboundSchema:
  z.ZodMiniType<TenantPaymentScreeningSubjectProjection, unknown> = z.object({
    status: TenantPaymentScreeningSubjectProjectionStatusEnum$inboundSchema,
  });

export function tenantPaymentScreeningSubjectProjectionFromJSON(
  jsonString: string,
): SafeParseResult<
  TenantPaymentScreeningSubjectProjection,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TenantPaymentScreeningSubjectProjection$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TenantPaymentScreeningSubjectProjection' from JSON`,
  );
}
