/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 655572fce415
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `not_enforced` - not_enforced
 *
 * @remarks
 * * `allowed` - allowed
 * * `not_allowed` - not_allowed
 * * `unavailable` - unavailable
 */
export const TenantPaymentScreeningSubjectProjectionStatusEnum = {
  NotEnforced: "not_enforced",
  Allowed: "allowed",
  NotAllowed: "not_allowed",
  Unavailable: "unavailable",
} as const;
/**
 * * `not_enforced` - not_enforced
 *
 * @remarks
 * * `allowed` - allowed
 * * `not_allowed` - not_allowed
 * * `unavailable` - unavailable
 */
export type TenantPaymentScreeningSubjectProjectionStatusEnum = OpenEnum<
  typeof TenantPaymentScreeningSubjectProjectionStatusEnum
>;

/** @internal */
export const TenantPaymentScreeningSubjectProjectionStatusEnum$inboundSchema:
  z.ZodMiniType<TenantPaymentScreeningSubjectProjectionStatusEnum, unknown> =
    openEnums.inboundSchema(TenantPaymentScreeningSubjectProjectionStatusEnum);
