/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c4e5a5fa3544
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `not_created` - not_created
 *
 * @remarks
 * * `created` - created
 */
export const TenantPaymentFulfillmentProjectionStatusEnum = {
  NotCreated: "not_created",
  Created: "created",
} as const;
/**
 * * `not_created` - not_created
 *
 * @remarks
 * * `created` - created
 */
export type TenantPaymentFulfillmentProjectionStatusEnum = OpenEnum<
  typeof TenantPaymentFulfillmentProjectionStatusEnum
>;

/** @internal */
export const TenantPaymentFulfillmentProjectionStatusEnum$inboundSchema:
  z.ZodMiniType<TenantPaymentFulfillmentProjectionStatusEnum, unknown> =
    openEnums.inboundSchema(TenantPaymentFulfillmentProjectionStatusEnum);
