/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `healthy` - healthy
 *
 * @remarks
 * * `degraded` - degraded
 * * `indexer_disabled` - indexer_disabled
 * * `awaiting_first_observation` - awaiting_first_observation
 * * `wallet_version_unavailable` - wallet_version_unavailable
 */
export const TrackingStatusEnum = {
  Healthy: "healthy",
  Degraded: "degraded",
  IndexerDisabled: "indexer_disabled",
  AwaitingFirstObservation: "awaiting_first_observation",
  WalletVersionUnavailable: "wallet_version_unavailable",
} as const;
/**
 * * `healthy` - healthy
 *
 * @remarks
 * * `degraded` - degraded
 * * `indexer_disabled` - indexer_disabled
 * * `awaiting_first_observation` - awaiting_first_observation
 * * `wallet_version_unavailable` - wallet_version_unavailable
 */
export type TrackingStatusEnum = OpenEnum<typeof TrackingStatusEnum>;

/** @internal */
export const TrackingStatusEnum$inboundSchema: z.ZodMiniType<
  TrackingStatusEnum,
  unknown
> = openEnums.inboundSchema(TrackingStatusEnum);
