/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 82a095eaf9a6
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { BalanceAsset, BalanceAsset$inboundSchema } from "./balance-asset.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ObservationStateEnum,
  ObservationStateEnum$inboundSchema,
} from "./observation-state-enum.js";
import {
  WalletFencedChainReseedContext,
  WalletFencedChainReseedContext$inboundSchema,
} from "./wallet-fenced-chain-reseed-context.js";
import {
  WalletObservationFinalityEnum,
  WalletObservationFinalityEnum$inboundSchema,
} from "./wallet-observation-finality-enum.js";
import {
  WalletVersionBalance,
  WalletVersionBalance$inboundSchema,
} from "./wallet-version-balance.js";

export type WalletBalanceResponse = {
  walletId: string;
  network: string;
  walletAddress: string | null;
  /**
   * * `latest` - latest
   *
   * @remarks
   * * `confirmed` - confirmed
   * * `finalized` - finalized
   */
  requestedFinality: WalletObservationFinalityEnum;
  /**
   * * `healthy` - healthy
   *
   * @remarks
   * * `degraded` - degraded
   * * `unavailable` - unavailable
   */
  observationState: ObservationStateEnum;
  observedAt: Date | null;
  assets: Array<BalanceAsset>;
  walletVersions: Array<WalletVersionBalance>;
  reseedContexts: Array<WalletFencedChainReseedContext>;
};

/** @internal */
export const WalletBalanceResponse$inboundSchema: z.ZodMiniType<
  WalletBalanceResponse,
  unknown
> = z.pipe(
  z.object({
    wallet_id: types.string(),
    network: types.string(),
    wallet_address: types.nullable(types.string()),
    requested_finality: WalletObservationFinalityEnum$inboundSchema,
    observation_state: ObservationStateEnum$inboundSchema,
    observed_at: types.nullable(types.date()),
    assets: z.array(BalanceAsset$inboundSchema),
    wallet_versions: z.array(WalletVersionBalance$inboundSchema),
    reseed_contexts: z.array(WalletFencedChainReseedContext$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "wallet_id": "walletId",
      "wallet_address": "walletAddress",
      "requested_finality": "requestedFinality",
      "observation_state": "observationState",
      "observed_at": "observedAt",
      "wallet_versions": "walletVersions",
      "reseed_contexts": "reseedContexts",
    });
  }),
);

export function walletBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletBalanceResponse' from JSON`,
  );
}
