/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 42903d141792
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WalletObservationFinalityEnum,
  WalletObservationFinalityEnum$inboundSchema,
} from "./wallet-observation-finality-enum.js";
import {
  WalletVersionStateEnum,
  WalletVersionStateEnum$inboundSchema,
} from "./wallet-version-state-enum.js";

export type WalletFencedChainReseedContext = {
  checkpointId: string;
  network: string;
  /**
   * * `latest` - latest
   *
   * @remarks
   * * `confirmed` - confirmed
   * * `finalized` - finalized
   */
  finality: WalletObservationFinalityEnum;
  manifestDigest: string;
  policyDigest: string;
  expectedGeneration: number;
  expectedNextBlockNumber: string;
  expectedLastScannedBlockNumber: string | null;
  expectedLastScannedBlockHash: string;
  expectedReviewRequiredAt: Date;
  expectedReviewErrorCode: string;
  observedAt: Date;
  walletVersionId: string;
  walletVersion: number;
  walletAddress: string;
  /**
   * * `pending` - pending
   *
   * @remarks
   * * `active` - active
   * * `draining` - draining
   * * `revoked` - revoked
   */
  walletVersionState: WalletVersionStateEnum;
};

/** @internal */
export const WalletFencedChainReseedContext$inboundSchema: z.ZodMiniType<
  WalletFencedChainReseedContext,
  unknown
> = z.pipe(
  z.object({
    checkpoint_id: types.string(),
    network: types.string(),
    finality: WalletObservationFinalityEnum$inboundSchema,
    manifest_digest: types.string(),
    policy_digest: types.string(),
    expected_generation: types.number(),
    expected_next_block_number: types.string(),
    expected_last_scanned_block_number: types.nullable(types.string()),
    expected_last_scanned_block_hash: types.string(),
    expected_review_required_at: types.date(),
    expected_review_error_code: types.string(),
    observed_at: types.date(),
    wallet_version_id: types.string(),
    wallet_version: types.number(),
    wallet_address: types.string(),
    wallet_version_state: WalletVersionStateEnum$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "checkpoint_id": "checkpointId",
      "manifest_digest": "manifestDigest",
      "policy_digest": "policyDigest",
      "expected_generation": "expectedGeneration",
      "expected_next_block_number": "expectedNextBlockNumber",
      "expected_last_scanned_block_number": "expectedLastScannedBlockNumber",
      "expected_last_scanned_block_hash": "expectedLastScannedBlockHash",
      "expected_review_required_at": "expectedReviewRequiredAt",
      "expected_review_error_code": "expectedReviewErrorCode",
      "observed_at": "observedAt",
      "wallet_version_id": "walletVersionId",
      "wallet_version": "walletVersion",
      "wallet_address": "walletAddress",
      "wallet_version_state": "walletVersionState",
    });
  }),
);

export function walletFencedChainReseedContextFromJSON(
  jsonString: string,
): SafeParseResult<WalletFencedChainReseedContext, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletFencedChainReseedContext$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletFencedChainReseedContext' from JSON`,
  );
}
