/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 413bd640a51a
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `active` - active
 *
 * @remarks
 * * `draining` - draining
 */
export const WalletVersionBalanceStateEnum = {
  Active: "active",
  Draining: "draining",
} as const;
/**
 * * `active` - active
 *
 * @remarks
 * * `draining` - draining
 */
export type WalletVersionBalanceStateEnum = OpenEnum<
  typeof WalletVersionBalanceStateEnum
>;

/** @internal */
export const WalletVersionBalanceStateEnum$inboundSchema: z.ZodMiniType<
  WalletVersionBalanceStateEnum,
  unknown
> = openEnums.inboundSchema(WalletVersionBalanceStateEnum);
