/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b0ca6eafbbab
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { BalanceAsset, BalanceAsset$inboundSchema } from "./balance-asset.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ObservationStateEnum,
  ObservationStateEnum$inboundSchema,
} from "./observation-state-enum.js";
import {
  WalletObservationFinalityEnum,
  WalletObservationFinalityEnum$inboundSchema,
} from "./wallet-observation-finality-enum.js";
import {
  WalletVersionBalanceStateEnum,
  WalletVersionBalanceStateEnum$inboundSchema,
} from "./wallet-version-balance-state-enum.js";

export type ReseedContext = {
  checkpointId: string;
  network: string;
  /**
   * * `latest` - latest
   *
   * @remarks
   * * `confirmed` - confirmed
   * * `finalized` - finalized
   */
  finality: WalletObservationFinalityEnum;
  manifestDigest: string;
  policyDigest: string;
  expectedGeneration: number;
  expectedNextBlockNumber: string;
  expectedLastScannedBlockNumber: string | null;
  expectedLastScannedBlockHash: string;
  expectedReviewRequiredAt: Date;
  expectedReviewErrorCode: string;
  observedAt: Date;
};

export type WalletVersionBalance = {
  walletVersionId: string;
  version: number;
  walletAddress: string;
  /**
   * * `active` - active
   *
   * @remarks
   * * `draining` - draining
   */
  state: WalletVersionBalanceStateEnum;
  /**
   * * `healthy` - healthy
   *
   * @remarks
   * * `degraded` - degraded
   * * `unavailable` - unavailable
   */
  observationState: ObservationStateEnum;
  observedAt: Date | null;
  assets: Array<BalanceAsset>;
  reseedContext: ReseedContext | null;
};

/** @internal */
export const ReseedContext$inboundSchema: z.ZodMiniType<
  ReseedContext,
  unknown
> = z.pipe(
  z.object({
    checkpoint_id: types.string(),
    network: types.string(),
    finality: WalletObservationFinalityEnum$inboundSchema,
    manifest_digest: types.string(),
    policy_digest: types.string(),
    expected_generation: types.number(),
    expected_next_block_number: types.string(),
    expected_last_scanned_block_number: types.nullable(types.string()),
    expected_last_scanned_block_hash: types.string(),
    expected_review_required_at: types.date(),
    expected_review_error_code: types.string(),
    observed_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "checkpoint_id": "checkpointId",
      "manifest_digest": "manifestDigest",
      "policy_digest": "policyDigest",
      "expected_generation": "expectedGeneration",
      "expected_next_block_number": "expectedNextBlockNumber",
      "expected_last_scanned_block_number": "expectedLastScannedBlockNumber",
      "expected_last_scanned_block_hash": "expectedLastScannedBlockHash",
      "expected_review_required_at": "expectedReviewRequiredAt",
      "expected_review_error_code": "expectedReviewErrorCode",
      "observed_at": "observedAt",
    });
  }),
);

export function reseedContextFromJSON(
  jsonString: string,
): SafeParseResult<ReseedContext, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReseedContext$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReseedContext' from JSON`,
  );
}

/** @internal */
export const WalletVersionBalance$inboundSchema: z.ZodMiniType<
  WalletVersionBalance,
  unknown
> = z.pipe(
  z.object({
    wallet_version_id: types.string(),
    version: types.number(),
    wallet_address: types.string(),
    state: WalletVersionBalanceStateEnum$inboundSchema,
    observation_state: ObservationStateEnum$inboundSchema,
    observed_at: types.nullable(types.date()),
    assets: z.array(BalanceAsset$inboundSchema),
    reseed_context: types.nullable(z.lazy(() => ReseedContext$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "wallet_version_id": "walletVersionId",
      "wallet_address": "walletAddress",
      "observation_state": "observationState",
      "observed_at": "observedAt",
      "reseed_context": "reseedContext",
    });
  }),
);

export function walletVersionBalanceFromJSON(
  jsonString: string,
): SafeParseResult<WalletVersionBalance, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletVersionBalance$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletVersionBalance' from JSON`,
  );
}
