/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4aa846c6d84b
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `pending` - pending
 *
 * @remarks
 * * `active` - active
 * * `draining` - draining
 * * `revoked` - revoked
 */
export const WalletVersionStateEnum = {
  Pending: "pending",
  Active: "active",
  Draining: "draining",
  Revoked: "revoked",
} as const;
/**
 * * `pending` - pending
 *
 * @remarks
 * * `active` - active
 * * `draining` - draining
 * * `revoked` - revoked
 */
export type WalletVersionStateEnum = OpenEnum<typeof WalletVersionStateEnum>;

/** @internal */
export const WalletVersionStateEnum$inboundSchema: z.ZodMiniType<
  WalletVersionStateEnum,
  unknown
> = openEnums.inboundSchema(WalletVersionStateEnum);
