/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 59a3551d18d1
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * * `latest` - latest
 *
 * @remarks
 * * `confirmed` - confirmed
 * * `finalized` - finalized
 */
export const WalletObservationFinalityEnum = {
  Latest: "latest",
  Confirmed: "confirmed",
  Finalized: "finalized",
} as const;
/**
 * * `latest` - latest
 *
 * @remarks
 * * `confirmed` - confirmed
 * * `finalized` - finalized
 */
export type WalletObservationFinalityEnum = OpenEnum<
  typeof WalletObservationFinalityEnum
>;

/** @internal */
export const WalletObservationFinalityEnum$inboundSchema: z.ZodMiniType<
  WalletObservationFinalityEnum,
  unknown
> = openEnums.inboundSchema(WalletObservationFinalityEnum);
